export const EN = [
  {
    text: "Networking & Content Delivery",
    collapsed: true,
    base: "/aws/networking-&-content-delivery/",
    items: [
      { text: 'VPC', link: 'vpc' },
      { text: 'CloudFront', link: 'cloudfront' },
      { text: 'API Gateway', link: 'api-gateway' },
      { text: 'Direct Connect', link: 'direct-connect' },
      { text: 'AWS App Mesh', link: 'aws-app-mesh' },
      { text: 'Global Accelerator', link: 'global-accelerator' },
      { text: 'Route 53', link: 'route-53' },
      { text: 'AWS Data Transfer Terminal', link: 'aws-data-transfer-terminal' },
      { text: 'AWS Private 5G', link: 'aws-private-5g' },
      { text: 'AWS Cloud Map', link: 'aws-cloud-map' },
      { text: 'Application Recovery Controller', link: 'application-recovery-controller' },
    ],
    link: 'index'
  },   
  // {
  //   text: 'Compute',
  //   collapsed: true,
  //   items: [
  //     { text: 'Compute', link: '/aws/compute/compute' },
  //     { text: 'EC2', link: '/aws/compute/ec2' },
  //     { text: 'Lightsail', link: '/aws/compute/lightsail' },
  //     { text: 'Lambda', link: '/aws/compute/lambda' },
  //     { text: 'Batch', link: '/aws/compute/batch' },
  //     { text: 'Elastic Beanstalk', link: '/aws/compute/elastic-beanstalk' },
  //     { text: 'Serverless Application', link: '/aws/compute/serverless-application' },
  //     { text: 'AWS Outposts', link: '/aws/compute/aws-outposts' },
  //     { text: 'EC2 Image Builder', link: '/aws/compute/ec2-image-builder' },
  //     { text: 'AWS App Runner', link: '/aws/compute/aws-app-runner' },
  //     { text: 'AWS SimSpace Weaver', link: '/aws/compute/aws-simspace-weaver' },
  //     { text: 'Parallel Computing Service', link: '/aws/compute/parallel-computing-service' },
  //     { text: 'EC2 Global View', link: '/aws/compute/ec2-global-view' },
  //   ]
  // },
  // {
  //   text: 'Containers',
  //   collapsed: true,
  //   items: [
  //     { text: 'Containers', link: '/aws/containers/containers' },
  //     { text: 'Elastic Container Service', link: '/aws/containers/elastic-container-service' },
  //     { text: 'Elastic Kubernetes Service', link: '/aws/containers/elastic-kubernetes-service' },
  //     { text: 'Red Hat OpenShift Service on AWS', link: '/aws/containers/red-hat-openshift-service-on-aws' },
  //     { text: 'Elastic Container Registry', link: '/aws/containers/elastic-container-registry' },
  //   ]
  // },
  // {
  //   text: "Storage",
  //   collapsed: true,
  //   items: [
  //     { text: 'Storage', link: '/aws/storage/storage' },
  //     { text: 'S3', link: '/aws/storage/s3' },
  //     { text: 'EFS', link: '/aws/storage/efs' },
  //     { text: 'FSx', link: '/aws/storage/fsx' },
  //     { text: 'S3 Glacier', link: '/aws/storage/s3-glacier' },
  //     { text: 'Storage Gateway', link: '/aws/storage/storage-gateway' },
  //     { text: 'AWS Backup', link: '/aws/storage/aws-backup' },
  //     { text: 'AWS Elastic Disaster Recovery', link: '/aws/storage/aws-elastic-disaster-recovery' },
  //   ]
  // },
  // {
  //   text: "Database",
  //   collapsed: true,
  //   items: [
  //     { text: 'Database', link: '/aws/database/database' },
  //     { text: 'Aurora and RDS', link: '/aws/database/aurora-and-rds' },
  //     { text: 'ElastiCache', link: '/aws/database/elasticache' },
  //     { text: 'Neptune', link: '/aws/database/neptune' },
  //     { text: 'Amazon QLDB', link: '/aws/database/amazon-qldb' },
  //     { text: 'Amazon DocumentDB', link: '/aws/database/amazon-documentdb' },
  //     { text: 'Amazon Keyspaces', link: '/aws/database/amazon-keyspaces' },
  //     { text: 'Amazon Timestream', link: '/aws/database/amazon-timestream' },
  //     { text: 'DynamoDB', link: '/aws/database/dynamodb' },
  //     { text: 'Aurora DSQL', link: '/aws/database/aurora-dsql' },
  //     { text: 'Amazon MemoryDB', link: '/aws/database/amazon-memorydb' },
  //     { text: 'Oracle Database@AWS', link: '/aws/database/oracle-database-aws' },
  //   ]              
  // },
  // {
  //   text: "Migration & Transfer",
  //   collapsed: true,
  //   items: [
  //     { text: 'Migration & Transfer', link: '/aws/migration-&-transfer/migration-&-transfer' },
  //     { text: 'AWS Migration Hub', link: '/aws/migration-&-transfer/aws-migration-hub' },
  //     { text: 'AWS Application Migration Service', link: '/aws/migration-&-transfer/aws-application-migration-service' },
  //     { text: 'Application Discovery Service', link: '/aws/migration-&-transfer/application-discovery-service' },
  //     { text: 'Database Migration Service', link: '/aws/migration-&-transfer/database-migration-service' },
  //     { text: 'AWS Transfer Family', link: '/aws/migration-&-transfer/aws-transfer-family' },
  //     { text: 'AWS Snow Family', link: '/aws/migration-&-transfer/aws-snow-family' },
  //     { text: 'DataSync', link: '/aws/migration-&-transfer/datasync' },
  //     { text: 'AWS Mainframe Modernization', link: '/aws/migration-&-transfer/aws-mainframe-modernization' },
  //     { text: 'Amazon Elastic VMware Service (Preview)', link: '/aws/migration-&-transfer/amazon-elastic-vmware-service' },
  //   ]
  // },
  // {
  //   text: "Developer Tools",
  //   collapsed: true,
  //   items: [
  //     { text: 'Developer Tools', link: '/aws/developer-tools/developer-tools' },
  //     { text: 'CodeCommit', link: '/aws/developer-tools/codecommit' },
  //     { text: 'CodeBuild', link: '/aws/developer-tools/codebuild' },
  //     { text: 'CodeDeploy', link: '/aws/developer-tools/codedeploy' },
  //     { text: 'CodePipeline', link: '/aws/developer-tools/codepipeline' },
  //     { text: 'Cloud9', link: '/aws/developer-tools/cloud9' },
  //     { text: 'CloudShell', link: '/aws/developer-tools/cloudshell' },
  //     { text: 'X-Ray', link: '/aws/developer-tools/x-ray' },
  //     { text: 'AWS FIS', link: '/aws/developer-tools/aws-fis' },
  //     { text: 'Infrastructure Composer', link: '/aws/developer-tools/infrastructure-composer' },
  //     { text: 'AWS App Studio', link: '/aws/developer-tools/aws-app-studio' },
  //     { text: 'AWS AppConfig', link: '/aws/developer-tools/aws-appconfig' },
  //     { text: 'CodeArtifact', link: '/aws/developer-tools/codeartifact' },
  //     { text: 'Amazon CodeCatalyst', link: '/aws/developer-tools/amazon-codecatalyst' },
  //     { text: 'Amazon Q Developer', link: '/aws/developer-tools/amazon-q-developer' },
  //   ]
  // },
  // {
  //   text: "Customer Enablement",
  //   collapsed: true,
  //   items: [
  //     { text: 'Customer Enablement', link: '/aws/customer-enablement/customer-enablement' },
  //     { text: 'AWS IQ', link: '/aws/customer-enablement/aws-iq' },
  //     { text: 'Managed Services', link: '/aws/customer-enablement/managed-services' },
  //     { text: 'Activate for Startups', link: '/aws/customer-enablement/activate-for-startups' },
  //     { text: 'AWS re:Post Private', link: '/aws/customer-enablement/aws-re-post-private' },
  //     { text: 'Support', link: '/aws/customer-enablement/support' },
  //   ]
  // },
  // {
  //   text: "Robotics",
  //   collapsed: true,
  //   items: [
  //     { text: 'Robotics', link: '/aws/robotics/robotics' },
  //     { text: 'AWS RoboMaker', link: '/aws/robotics/aws-robomaker' },
  //   ]
  // },
  // {
  //   text: "Blockchain",
  //   collapsed: true,
  //   items: [
  //     { text: 'Blockchain', link: '/aws/blockchain/blockchain' },
  //     { text: 'Amazon Managed Blockchain', link: '/aws/blockchain/amazon-managed-blockchain' },
  //   ]
  // },
  // {
  //   text: "Satellite",
  //   collapsed: true,
  //   items: [
  //     { text: 'Satellite', link: '/aws/satellite/satellite' },
  //     { text: 'Ground Station', link: '/aws/satellite/ground-station' },
  //   ]
  // },    
  // {
  //   text: "Quantum Technologies",
  //   collapsed: true,
  //   items: [
  //     { text: 'Quantum Technologies', link: '/aws/quantum-technologies/quantum-technologies' },
  //     { text: 'Amazon Braket', link: '/aws/quantum-technologies/amazon-braket' },
  //   ]
  // },    
  // {
  //   text: "Management & Governance",
  //   collapsed: true,
  //   items: [
  //     { text: 'Management & Governance', link: '/aws/management-&-governance/management-&-governance' },
  //     { text: 'AWS Organizations', link: '/aws/management-&-governance/aws-organizations' },
  //     { text: 'CloudWatch', link: '/aws/management-&-governance/cloudwatch' },
  //     { text: 'AWS Auto Scaling', link: '/aws/management-&-governance/aws-auto-scaling' },
  //     { text: 'CloudFormation', link: '/aws/management-&-governance/cloudformation' },
  //     { text: 'AWS Config', link: '/aws/management-&-governance/aws-config' },
  //     { text: 'OpsWorks', link: '/aws/management-&-governance/opsworks' },
  //     { text: 'Service Catalog', link: '/aws/management-&-governance/service-catalog' },
  //     { text: 'Systems Manager', link: '/aws/management-&-governance/systems-manager' },
  //     { text: 'Trusted Advisor', link: '/aws/management-&-governance/trusted -advisor' },
  //     { text: 'Control Tower', link: '/aws/management-&-governance/control-tower' },
  //     { text: 'AWS Well-Architected Tool', link: '/aws/management-&-governance/aws-well-architected-tool' },
  //     { text: 'Amazon Q Developer in chat applications', link: '/aws/management-&-governance/amazon-q-developer-in-chat-applications' },
  //     { text: 'Launch Wizard', link: '/aws/management-&-governance/launch-wizard' },
  //     { text: 'AWS Compute Optimizer', link: '/aws/management-&-governance/aws-compute-optimizer' },
  //     { text: 'Resource Groups & Tag Editor', link: '/aws/management-&-governance/resource-groups-&-tag-editor' },
  //     { text: 'Amazon Grafana', link: '/aws/management-&-governance/amazon-grafana' },
  //     { text: 'Amazon Prometheus', link: '/aws/management-&-governance/amazon-prometheus' },
  //     { text: 'AWS Resilience Hub', link: '/aws/management-&-governance/aws-resilience-hub' },
  //     { text: 'Incident Manager', link: '/aws/management-&-governance/incident-manager' },
  //     { text: 'AWS Telco Network Builder', link: '/aws/management-&-governance/aws-telco-network-builder' },
  //     { text: 'AWS Health Dashboard', link: '/aws/management-&-governance/aws-health-dashboard' },
  //     { text: 'AWS Proton', link: '/aws/management-&-governance/aws-proton' },
  //     { text: 'AWS User Notifications', link: '/aws/management-&-governance/aws-user-notifications' },
  //     { text: 'CloudTrail', link: '/aws/management-&-governance/cloudtrail' },
  //     { text: 'AWS License Manager', link: '/aws/management-&-governance/aws-license-manager' },
  //     { text: 'AWS Resource Explorer', link: '/aws/management-&-governance/aws-resource-explorer' },
  //     { text: 'Service Quotas', link: '/aws/management-&-governance/service-quotas' },
  //   ]
  // },        
  // {
  //   text: "Media Services",
  //   collapsed: true,
  //   items: [
  //     { text: 'Media Services', link: '/aws/media-services/media-services' },
  //     { text: 'Kinesis Video Streams', link: '/aws/media-services/kinesis-video-streams' },
  //     { text: 'MediaConvert', link: '/aws/media-services/mediaconvert' },
  //     { text: 'MediaLive', link: '/aws/media-services/medialive' },
  //     { text: 'MediaPackage', link: '/aws/media-services/mediapackage' },
  //     { text: 'MediaStore', link: '/aws/media-services/mediastore' },
  //     { text: 'MediaTailor', link: '/aws/media-services/mediatailor' },
  //     { text: 'Elemental Appliances & Software', link: '/aws/media-services/elemental-appliances-&-software' },
  //     { text: 'Elastic Transcoder', link: '/aws/media-services/elastic-transcoder' },
  //     { text: 'Amazon Interactive Video Service', link: '/aws/media-services/amazon-interactive-video-service' },
  //     { text: 'AWS Deadline Cloud', link: '/aws/media-services/aws-deadline-cloud' },
  //     { text: 'MediaConnect', link: '/aws/media-services/mediaconnect' },
  //   ]
  // },  
  // {
  //   text: "Machine Learning",
  //   collapsed: true,
  //   items: [
  //     { text: 'Machine Learning', link: '/aws/machine-learning/machine-learning' },
  //     { text: 'Amazon SageMaker AI', link: '/aws/machine-learning/amazon-sagemaker-ai' },
  //     { text: 'Amazon Augmented AI', link: '/aws/machine-learning/amazon-augmented-ai' },
  //     { text: 'Amazon CodeGuru', link: '/aws/machine-learning/amazon-codeguru' },
  //     { text: 'Amazon DevOps Guru', link: '/aws/machine-learning/amazon-devops-guru' },
  //     { text: 'Amazon Comprehend', link: '/aws/machine-learning/amazon-comprehend' },
  //     { text: 'Amazon Forecast', link: '/aws/machine-learning/amazon-forecast' },
  //     { text: 'Amazon Fraud Detector', link: '/aws/machine-learning/amazon-fraud-detector' },
  //     { text: 'Amazon Kendra', link: '/aws/machine-learning/amazon-kendra' },
  //     { text: 'Amazon Personalize', link: '/aws/machine-learning/amazon-personalize' },
  //     { text: 'Amazon Polly', link: '/aws/machine-learning/amazon-polly' },
  //     { text: 'Amazon Rekognition', link: '/aws/machine-learning/amazon-rekognition' },
  //     { text: 'Amazon Textract', link: '/aws/machine-learning/amazon-textract' },
  //     { text: 'Amazon Transcribe', link: '/aws/machine-learning/amazon-transcribe' },
  //     { text: 'Amazon Translate', link: '/aws/machine-learning/amazon-translate' },
  //     { text: 'AWS DeepComposer', link: '/aws/machine-learning/aws-deepcomposer' },
  //     { text: 'AWS DeepRacer', link: '/aws/machine-learning/aws-deepracer' },
  //     { text: 'AWS Panorama', link: '/aws/machine-learning/aws-panorama' },
  //     { text: 'Amazon Monitron', link: '/aws/machine-learning/amazon-monitron' },
  //     { text: 'AWS HealthLake', link: '/aws/machine-learning/aws-healthlake' },
  //     { text: 'Amazon Lookout for Vision', link: '/aws/machine-learning/amazon-lookout-for-vision' },
  //     { text: 'Amazon Lookout for Equipment', link: '/aws/machine-learning/amazon-lookout-for-equipment' },
  //     { text: 'Amazon Lookout for Metrics', link: '/aws/machine-learning/amazon-lookout-for-metrics' },
  //     { text: 'Amazon Q Business', link: '/aws/machine-learning/amazon-q-business' },
  //     { text: 'AWS HealthOmics', link: '/aws/machine-learning/aws-healthomics' },
  //     { text: 'Amazon Bedrock', link: '/aws/machine-learning/amazon-bedrock' },
  //     { text: 'Amazon Q', link: '/aws/machine-learning/amazon-q' },
  //     { text: 'Amazon Comprehend Medical', link: '/aws/machine-learning/amazon-comprehend-medical' },
  //     { text: 'Amazon Lex', link: '/aws/machine-learning/amazon-lex' },
  //     { text: 'AWS HealthImaging', link: '/aws/machine-learning/aws-healthimaging' },
  //   ]
  // },  
  // {
  //   text: "Analytics",
  //   collapsed: true,
  //   items: [
  //     { text: 'Analytics', link: '/aws/analytics/analytics' },
  //     { text: 'Athena', link: '/aws/analytics/athena' },
  //     { text: 'Amazon Redshift', link: '/aws/analytics/amazon-redshift' },
  //     { text: 'CloudSearch', link: '/aws/analytics/cloudsearch' },
  //     { text: 'Amazon OpenSearch Service', link: '/aws/analytics/amazon-opensearch-service' },
  //     { text: 'Kinesis', link: '/aws/analytics/kinesis' },
  //     { text: 'QuickSight', link: '/aws/analytics/quicksight' },
  //     { text: 'AWS Data Exchange', link: '/aws/analytics/aws-data-exchange' },
  //     { text: 'AWS Lake Formation', link: '/aws/analytics/aws-lake-formation' },
  //     { text: 'MSK', link: '/aws/analytics/msk' },
  //     { text: 'AWS Glue DataBrew', link: '/aws/analytics/aws-glue-databrew' },
  //     { text: 'Amazon FinSpace', link: '/aws/analytics/amazon-finspace' },
  //     { text: 'Managed Apache Flink', link: '/aws/analytics/managed-apache-flink' },
  //     { text: 'EMR', link: '/aws/analytics/emr' },
  //     { text: 'AWS Clean Rooms', link: '/aws/analytics/aws-clean-rooms' },
  //     { text: 'Amazon SageMaker', link: '/aws/analytics/amazon-sagemaker' },
  //     { text: 'AWS Entity Resolution', link: '/aws/analytics/aws-entity-resolution' },
  //     { text: 'AWS Glue', link: '/aws/analytics/aws-glue' },
  //     { text: 'Amazon Data Firehose', link: '/aws/analytics/amazon-data-firehose' },
  //     { text: 'Amazon DataZone', link: '/aws/analytics/amazon-datazone' },
  //   ]
  // },   
  // {
  //   text: "Security, Identity, & Compliance",
  //   collapsed: true,
  //   items: [
  //     { text: 'Security, Identity, & Compliance', link: '/aws/security-identity-&-compliance/security-identity-&-compliance' },
  //     { text: 'Resource Access Manager', link: '/aws/security-identity-&-compliance/resource-access-manager' },
  //     { text: 'Cognito', link: '/aws/security-identity-&-compliance/cognito' },
  //     { text: 'Secrets Manager', link: '/aws/security-identity-&-compliance/secrets-manager' },
  //     { text: 'GuardDuty', link: '/aws/security-identity-&-compliance/guardduty' },
  //     { text: 'Amazon Inspector', link: '/aws/security-identity-&-compliance/amazon-inspector' },
  //     { text: 'Amazon Macie', link: '/aws/security-identity-&-compliance/amazon-macie' },
  //     { text: 'IAM Identity Center', link: '/aws/security-identity-&-compliance/iam-identity-center' },
  //     { text: 'Certificate Manager', link: '/aws/security-identity-&-compliance/certificate-manager' },
  //     { text: 'Key Management Service', link: '/aws/security-identity-&-compliance/key-management-service' },
  //     { text: 'CloudHSM', link: '/aws/security-identity-&-compliance/cloudhsm' },
  //     { text: 'Directory Service', link: '/aws/security-identity-&-compliance/directory-service' },
  //     { text: 'AWS Firewall Manager', link: '/aws/security-identity-&-compliance/aws-firewall-manager' },
  //     { text: 'AWS Artifact', link: '/aws/security-identity-&-compliance/aws-artifact' },
  //     { text: 'Detective', link: '/aws/security-identity-&-compliance/detective' },
  //     { text: 'AWS Signer', link: '/aws/security-identity-&-compliance/aws-signer' },
  //     { text: 'Security Lake', link: '/aws/security-identity-&-compliance/security-lake' },
  //     { text: 'WAF & Shield', link: '/aws/security-identity-&-compliance/waf-&-shield' },
  //     { text: 'Amazon Verified Permissions', link: '/aws/security-identity-&-compliance/amazon-verified-permissions' },
  //     { text: 'AWS Audit Manager', link: '/aws/security-identity-&-compliance/aws-audit-manager' },
  //     { text: 'Security Hub', link: '/aws/security-identity-&-compliance/security-hub' },
  //     { text: 'IAM', link: '/aws/security-identity-&-compliance/iam' },
  //     { text: 'AWS Private Certificate Authority', link: '/aws/security-identity-&-compliance/aws-private-certificate-authority' },
  //     { text: 'AWS Payment Cryptography', link: '/aws/security-identity-&-compliance/aws-payment-cryptography' },
  //     { text: 'AWS Security Incident Response', link: '/aws/security-identity-&-compliance/aws-security-incident-response' },
  //   ]
  // },   
  // {
  //   text: "Cloud Financial Management",
  //   collapsed: true,
  //   items: [
  //     { text: 'Cloud Financial Management', link: '/aws/cloud-financial-management/cloud-financial-management' },
  //     { text: 'AWS Marketplace', link: '/aws/cloud-financial-management/aws-marketplace' },
  //     { text: 'AWS Billing Conductor', link: '/aws/cloud-financial-management/aws-billing-conductor' },
  //     { text: 'Billing and Cost Management', link: '/aws/cloud-financial-management/billing-and-cost-management' },
  //   ]
  // },     
  // {
  //   text: "Front-end Web & Mobile",
  //   collapsed: true,
  //   items: [
  //     { text: 'Front-end Web & Mobile', link: '/aws/front-end-web-&-mobile/front-end-web-&-mobile' },
  //     { text: 'AWS Amplify', link: '/aws/front-end-web-&-mobile/aws-amplify' },
  //     { text: 'AWS AppSync', link: '/aws/front-end-web-&-mobile/aws-appsync' },
  //     { text: 'Device Farm', link: '/aws/front-end-web-&-mobile/device-farm' },
  //     { text: 'Amazon Location Service', link: '/aws/front-end-web-&-mobile/amazon-location-service' },
  //   ]
  // },  
  // {
  //   text: "Application Integration",
  //   collapsed: true,
  //   items: [
  //     { text: 'Application Integration', link: '/aws/application-integration/application-integration' },
  //     { text: 'Step Functions', link: '/aws/application-integration/step-functions' },
  //     { text: 'Amazon AppFlow', link: '/aws/application-integration/amazon-appflow' },
  //     { text: 'Amazon MQ', link: '/aws/application-integration/amazon-mq' },
  //     { text: 'Simple Notification Service', link: '/aws/application-integration/simple-notification-service' },
  //     { text: 'Simple Queue Service', link: '/aws/application-integration/simple-queue-service' },
  //     { text: 'SWF', link: '/aws/application-integration/swf' },
  //     { text: 'Managed Apache Airflow', link: '/aws/application-integration/managed-apache-airflow' },
  //     { text: 'AWS B2B Data Interchange', link: '/aws/application-integration/aws-b2b-data-interchange' },
  //     { text: 'Amazon EventBridge', link: '/aws/application-integration/amazon-eventbridge' },
  //   ]
  // },  
  // {
  //   text: "Business Applications",
  //   collapsed: true,
  //   items: [
  //     { text: 'Business Applications', link: '/aws/business-applications/business-applications' },
  //     { text: 'Amazon Connect', link: '/aws/business-applications/amazon-connect' },
  //     { text: 'Amazon Chime', link: '/aws/business-applications/amazon-chime' },
  //     { text: 'Amazon Simple Email Service', link: '/aws/business-applications/amazon-simple-email-service' },
  //     { text: 'Amazon WorkDocs', link: '/aws/business-applications/amazon-workdocs' },
  //     { text: 'Amazon WorkMail', link: '/aws/business-applications/amazon-workmail' },
  //     { text: 'AWS Supply Chain', link: '/aws/business-applications/aws-supply-chain' },
  //     { text: 'Amazon Pinpoint', link: '/aws/business-applications/amazon-pinpoint' },
  //     { text: 'Amazon One Enterprise', link: '/aws/business-applications/amazon-one-enterprise' },
  //     { text: 'AWS Wickr', link: '/aws/business-applications/aws-wickr' },
  //     { text: 'AWS AppFabric', link: '/aws/business-applications/aws-appfabric' },
  //     { text: 'AWS End User Messaging', link: '/aws/business-applications/aws-end-user-messaging' },
  //     { text: 'Amazon Chime SDK', link: '/aws/business-applications/amazon-chime-sdk' },
  //   ]
  // },  
  // {
  //   text: "End User Computing",
  //   collapsed: true,
  //   items: [
  //     { text: 'End User Computing', link: '/aws/end-user-computing/end-user-computing' },
  //     { text: 'WorkSpaces', link: '/aws/end-user-computing/workspaces' },
  //     { text: 'AppStream 2.0', link: '/aws/end-user-computing/appstream' },
  //     { text: 'WorkSpaces Thin Client', link: '/aws/end-user-computing/workspaces-thin-client' },
  //     { text: 'WorkSpaces Secure Browser', link: '/aws/end-user-computing/workspaces-secure-browser' },
  //   ]
  // },  
  // {
  //   text: "Internet of Things",
  //   collapsed: true,
  //   items: [
  //     { text: 'Internet of Things', link: '/aws/internet-of-things/internet-of-things' },
  //     { text: 'IoT Analytics', link: '/aws/internet-of-things/iot-analytics' },
  //     { text: 'IoT Device Defender', link: '/aws/internet-of-things/iot-device-defender' },
  //     { text: 'IoT Device Management', link: '/aws/internet-of-things/iot-device-management' },
  //     { text: 'IoT Greengrass', link: '/aws/internet-of-things/iot-greengrass' },
  //     { text: 'IoT SiteWise', link: '/aws/internet-of-things/iot-sitewise' },
  //     { text: 'IoT Core', link: '/aws/internet-of-things/iot-core' },
  //     { text: 'IoT TwinMaker', link: '/aws/internet-of-things/iot-twinmaker' },
  //     { text: 'IoT Events', link: '/aws/internet-of-things/iot-events' },
  //     { text: 'AWS IoT FleetWise', link: '/aws/internet-of-things/aws-iot-fleetwise' },
  //   ]
  // },  
  // {
  //   text: "Game Development",
  //   collapsed: true,
  //   items: [
  //     { text: 'Game Development', link: '/aws/game-development/game-development' },
  //     { text: 'Amazon GameLift Servers', link: '/aws/game-development/amazon-gamelift-servers' },
  //     { text: 'Amazon GameLift Streams', link: '/aws/game-development/amazon-gamelift-streams' },
  //   ]
  // },                                   
] 
