import { defineConfig } from 'vitepress'
import { 
  GitAndGitHub,
  AWS 
} from './routes'

export default defineConfig({
  title: "JN-Trail-Compass",
  description: "A VitePress Site",
  themeConfig: {
    socialLinks: [
      { icon: 'github', link: 'https://github.com/vuejs/vitepress' }
    ]
  },
  base: '/jn-trail-compass/',
  locales: {
    root: {
      label: 'English',
      lang: 'en',
      link: '/',
      themeConfig: {
        sidebar: {
          '/git-&-github/': GitAndGitHub.EN,
          '/linux/': [
            { text: 'introduction-to-linux', link: '/linux/introduction-to-linux' },
            { text: 'basic-linux-commands', link: '/linux/basic-linux-commands' },
            { text: 'file-system-structure-and-permissions', link: '/linux/file-system-structure-and-permissions' },
            { text: 'user-management-and-groups', link: '/linux/user-management-and-groups' },
            { text: 'package-management', link: '/linux/package-management' },
            { text: 'advanced-file-permissions-and-access-control', link: '/linux/advanced-file-permissions-and-access-control' },
            { text: 'file-search', link: '/linux/file-search' },
            { text: 'file-compression-and-archiving', link: '/linux/file-compression-and-archiving' },
            { text: 'disk-management', link: '/linux/disk-management' },
            { text: 'backup-and-restore-data', link: '/linux/backup-and-restore-data' },
            { text: 'process-management', link: '/linux/process-management' },
            { text: 'system-services', link: '/linux/system-services' },
            { text: 'process-scheduling', link: '/linux/process-scheduling' },
            { text: 'cron', link: '/linux/cron' },
            { text: 'logs-and-system-monitoring', link: '/linux/logs-and-system-monitoring' },
            { text: 'managing-services', link: '/linux/managing-services' },
            { text: 'network-configuration', link: '/linux/network-configuration' },
            { text: 'firewall-configuration', link: '/linux/firewall-configuration' },
            { text: 'secure-ssh-access', link: '/linux/secure-ssh-access' },
            { text: 'file-encryption-and-secure-file-transfer', link: '/linux/file-encryption-and-secure-file-transfer' },
            { text: 'security-best-practices', link: '/linux/security-best-practices' },
            { text: 'performance-tuning', link: '/linux/performance-tuning' },
            { text: 'using-docker-with-linux', link: '/linux/using-docker-with-linux' },
            { text: 'virtualization-with-kvm', link: '/linux/virtualization-with-kvm' },
            { text: 'linux-kernel-compilation', link: '/linux/linux-kernel-compilation' },
            { text: 'system-monitoring-and-automation', link: '/linux/system-monitoring-and-automation' },
          ],
          '/docker/': [
            { text: 'introduction-to-docker', link: '/docker/introduction-to-docker' },
            { text: 'docker-architecture', link: '/docker/docker-architecture' },
            { text: 'docker-cli-basics', link: '/docker/docker-cli-basics' },
            { text: 'dockerfile-basics', link: '/docker/dockerfile-basics' },
            { text: 'creating-and-running-containers', link: '/docker/creating-and-running-containers' },
            { text: 'inspecting-containers', link: '/docker/inspecting-containers' },
            { text: 'working-with-images', link: '/docker/working-with-images' },
            { text: 'building-images', link: '/docker/building-images' },
            { text: 'volumes-and-persistent-storage', link: '/docker/volumes-and-persistent-storage' },
            { text: 'networking-basics', link: '/docker/networking-basics' },
            { text: 'exposing-ports', link: '/docker/exposing-ports' },
            { text: 'environment-variables', link: '/docker/environment-variables' },
            { text: 'introduction-to-docker-compose', link: '/docker/introduction-to-docker-compose' },
            { text: 'multi-container-applications', link: '/docker/multi-container-applications' },
            { text: 'managing-resources', link: '/docker/managing-resources' },
            { text: 'docker-compose-networking', link: '/docker/docker-compose-networking' },
            { text: 'docker-compose-volumes', link: '/docker/docker-compose-volumes' },
            { text: 'docker-compose-environment', link: '/docker/docker-compose-environment' },
            { text: 'optimizing-docker-images', link: '/docker/optimizing-docker-images' },
            { text: 'docker-registry', link: '/docker/docker-registry' },
            { text: 'docker-security', link: '/docker/docker-security' },
            { text: 'scaling-with-swarm', link: '/docker/scaling-with-swarm' },
          ],
          '/k8s/': [
            { text: 'introduction-to-kubernetes', link: '/k8s/introduction-to-kubernetes' },
            { text: 'kubernetes-architecture', link: '/k8s/kubernetes-architecture' },
            { text: 'kubernetes-architecture', link: '/k8s/kubernetes-architecture' },
            { text: 'installing-kubernetes', link: '/k8s/installing-kubernetes' },
            { text: 'kubectl-commands', link: '/k8s/kubectl-commands' },
            { text: 'pods', link: '/k8s/pods' },
            { text: 'deployments', link: '/k8s/deployments' },
            { text: 'replicasets', link: '/k8s/replicasets' },
            { text: 'services', link: '/k8s/services' },
            { text: 'configmaps', link: '/k8s/configmaps' },
            { text: 'secrets', link: '/k8s/secrets' },
            { text: 'volumes', link: '/k8s/volumes' },
            { text: 'persistent-volumes', link: '/k8s/persistent-volumes' },
            { text: 'namespaces', link: '/k8s/namespaces' },
            { text: 'resource-quotas', link: '/k8s/resource-quotas' },
            { text: 'scaling-applications', link: '/k8s/scaling-applications' },
            { text: 'networking-basics', link: '/k8s/networking-basics' },
            { text: 'monitoring-and-logging', link: '/k8s/monitoring-and-logging' },
            { text: 'ingress-controllers', link: '/k8s/ingress-controllers' },
            { text: 'statefulsets', link: '/k8s/statefulsets' },
            { text: 'daemonsets', link: '/k8s/daemonsets' },
            { text: 'jobs-and-cronjobs', link: '/k8s/jobs-and-cronjobs' },
            { text: 'advanced-deployments', link: '/k8s/advanced-deployments' },
            { text: 'custom-resource-definitions', link: '/k8s/custom-resource-definitions' },
            { text: 'scheduling', link: '/k8s/scheduling' },
            { text: 'security', link: '/k8s/security' },
            { text: 'deployment-patterns', link: '/k8s/deployment-patterns' },
            { text: 'backup-disaster-recovery', link: '/k8s/backup-disaster-recovery' },
            { text: 'multi-cluster-management', link: '/k8s/multi-cluster-management' },
            { text: 'helm', link: '/k8s/helm' },
          ],
          '/mongodb/': [
            { text: 'introduction-to-mongodb', link: '/mongodb/introduction-to-mongodb' },   
            { text: 'mongodb-architecture', link: '/mongodb/mongodb-architecture' }, 
            { text: 'database-and-collections', link: '/mongodb/database-and-collections' }, 
            { text: 'documents-and-bson', link: '/mongodb/documents-and-bson' }, 
            { text: 'basic-crud-operations', link: '/mongodb/basic-crud-operations' },
            { text: 'query-operators', link: '/mongodb/query-operators' },
            { text: 'mongodb-shell', link: '/mongodb/mongodb-shell' },
            { text: 'data-types', link: '/mongodb/data-types' },
            { text: 'indexes', link: '/mongodb/indexes' },
            { text: 'query-basics', link: '/mongodb/query-basics' },
            { text: 'aggregation-framework', link: '/mongodb/aggregation-framework' },
            { text: 'relationships', link: '/mongodb/relationships' },
            { text: 'transactions', link: '/mongodb/transactions' },
            { text: 'backup-and-restore', link: '/mongodb/backup-and-restore' },
            { text: 'schema-design', link: '/mongodb/schema-design' },
            { text: 'validation-rules', link: '/mongodb/validation-rules' },
            { text: 'replica-sets', link: '/mongodb/replica-sets' },
            { text: 'sharding', link: '/mongodb/sharding' },
            { text: 'performance-tuning', link: '/mongodb/performance-tuning' },
            { text: 'security', link: '/mongodb/security' },
            { text: 'advanced-aggregations', link: '/mongodb/advanced-aggregations' },
            { text: 'common-errors-debugging', link: '/mongodb/common-errors-debugging' },
          ],
          '/postgresql/': [
            { text: 'introduction-to-postgresql', link: '/postgresql/introduction-to-postgresql' },
            { text: 'postgresql-architecture', link: '/postgresql/postgresql-architecture' },
            { text: 'rdbms-concepts', link: '/postgresql/rdbms-concepts' },
            { text: 'object-model', link: '/postgresql/object-model' },
            { text: 'relational-model', link: '/postgresql/relational-model' },
            { text: 'high-level-database-concepts', link: '/postgresql/high-level-database-concepts' },
            { text: 'postgresql-tools', link: '/postgresql/postgresql-tools' },
            { text: 'basic-sql-commands', link: '/postgresql/basic-sql-commands' },
            { text: 'sorting-and-limiting', link: '/postgresql/sorting-and-limiting' },
            { text: 'basic-functions', link: '/postgresql/basic-functions' },
            { text: 'data-types', link: '/postgresql/data-types' },
            { text: 'constraints-and-keys', link: '/postgresql/constraints-and-keys' },
            { text: 'joins', link: '/postgresql/joins' },
            { text: 'aggregations', link: '/postgresql/aggregations' },
            { text: 'views', link: '/postgresql/views' },
            { text: 'indexing', link: '/postgresql/indexing' },
            { text: 'subqueries', link: '/postgresql/subqueries' },
            { text: 'stored-procedures', link: '/postgresql/stored-procedures' },
            { text: 'common-table-expressions', link: '/postgresql/common-table-expressions' },
            { text: 'transactions-and-acid-properties', link: '/postgresql/transactions-and-acid-properties' },
            { text: 'triggers', link: '/postgresql/triggers' },
            { text: 'json-and-jsonb', link: '/postgresql/json-and-jsonb' },
            { text: 'user-management', link: '/postgresql/user-management' },
            { text: 'backup-and-restore', link: '/postgresql/backup-and-restore' },
            { text: 'error-handling', link: '/postgresql/error-handling' },
            { text: 'authentication', link: '/postgresql/authentication' },
            { text: 'advanced-queries', link: '/postgresql/advanced-queries' },
            { text: 'data-security', link: '/postgresql/data-security' },
            { text: 'performance-optimization', link: '/postgresql/performance-optimization' },
            { text: 'replication', link: '/postgresql/replication' },
            { text: 'scaling', link: '/postgresql/scaling' },
          ],
          '/redis/': [
            { text: 'introduction-to-redis', link: '/redis/introduction-to-redis' },
            { text: 'in-memory-data-structure-store', link: '/redis/in-memory-data-structure-store' },
            { text: 'key-value-database', link: '/redis/key-value-database' },
            { text: 'cache', link: '/redis/cache' },
            { text: 'real-time-analytics', link: '/redis/real-time-analytics' },
            { text: 'session-management', link: '/redis/session-management' },
            { text: 'pub-sub-messaging', link: '/redis/pub-sub-messaging' },
            { text: 'leaderboards-and-counters', link: '/redis/leaderboards-and-counters' },
            { text: 'data-persistence-options', link: '/redis/data-persistence-options' },
            { text: 'rich-data-structures', link: '/redis/rich-data-structures' },
            { text: 'high-performance-and-scalability', link: '/redis/high-performance-and-scalability' },
            { text: 'redis-vs-sql-nosql-dbs', link: '/redis/redis-vs-sql-nosql-dbs' },
            { text: 'when-to-choose-redis', link: '/redis/when-to-choose-redis' },
            { text: 'using-package-managers', link: '/redis/using-package-managers' },
            { text: 'pre-compiled-binaries', link: '/redis/pre-compiled-binaries' },
            { text: 'using-docker', link: '/redis/using-docker' },
            { text: 'starting-the-server', link: '/redis/starting-the-server' },
            { text: 'connecting-using-redis-cli', link: '/redis/connecting-using-redis-cli' },
            { text: 'basic-commands-set-get', link: '/redis/basic-commands-set-get' },
            { text: 'del', link: '/redis/del' },
            { text: 'expire', link: '/redis/expire' },
            { text: 'ttl', link: '/redis/ttl' },
            { text: 'overview-of-data-types', link: '/redis/overview-of-data-types' },
            { text: 'strings', link: '/redis/strings' },
            { text: 'lists', link: '/redis/lists' },
            { text: 'sets', link: '/redis/sets' },
            { text: 'hashes', link: '/redis/hashes' },
            { text: 'sorted-sets', link: '/redis/sorted-sets' },
            { text: 'naming-conventions', link: '/redis/naming-conventions' },
            { text: 'retrieval-by-pattern', link: '/redis/retrieval-by-pattern' },
            { text: 'expiration', link: '/redis/expiration' },
            { text: 'atomicity-in-redis', link: '/redis/atomicity-in-redis' },
            { text: 'pipelining', link: '/redis/pipelining' },
            { text: 'batch-operations', link: '/redis/batch-operations' },
            { text: 'bitmaps', link: '/redis/bitmaps' },
            { text: 'hyperloglog', link: '/redis/hyperloglog' },
            { text: 'streams', link: '/redis/streams' },
            { text: 'geospatial-indexes', link: '/redis/geospatial-indexes' },
            { text: 'pub-sub', link: '/redis/pub-sub' },
            { text: 'transactions', link: '/redis/transactions' },
            { text: 'lua-scripting', link: '/redis/lua-scripting' },
            { text: 'persistence-options', link: '/redis/persistence-options' },
            { text: 'replication-basics', link: '/redis/replication-basics' },
            { text: 'sentinel', link: '/redis/sentinel' },
            { text: 'clustering', link: '/redis/clustering' },
            { text: 'ssl-tls-encryption', link: '/redis/ssl-tls-encryption' },
            { text: 'network-security', link: '/redis/network-security' },
            { text: 'authentication', link: '/redis/authentication' },
            { text: 'monitoring-and-optimization', link: '/redis/monitoring-and-optimization' },
            { text: 'modules', link: '/redis/modules' },
            { text: 'backup-and-recovery', link: '/redis/backup-and-recovery' },
            { text: 'upgrading-redis', link: '/redis/upgrading-redis' },
            { text: 'disaster-recovery', link: '/redis/disaster-recovery' },
          ],
          '/algorithm/': [
            { text: 'introduction-to-algorithms', link: '/algorithm/introduction-to-algorithms' },
            { text: 'time-and-space-complexity', link: '/algorithm/time-and-space-complexity' },
            { text: 'asymptotic-notations', link: '/algorithm/asymptotic-notations' },
            { text: 'arrays', link: '/algorithm/arrays' },
            { text: 'string', link: '/algorithm/string' },
            { text: 'linked-list', link: '/algorithm/linked-list' },
            { text: 'stacks-and-queues', link: '/algorithm/stacks-and-queues' },
            { text: 'recursion-and-divide-and-conquer-algorithms', link: '/algorithm/recursion-and-divide-and-conquer-algorithms' },
            { text: 'linear-search-and-binary-search', link: '/algorithm/linear-search-and-binary-search' },
            { text: 'sorting-algorithms', link: '/algorithm/sorting-algorithms' },
            { text: 'merge-sort-and-quick-sort', link: '/algorithm/merge-sort-and-quick-sort' },
            { text: 'heaps-and-priority-queues', link: '/algorithm/heaps-and-priority-queues' },
            { text: 'hashing-and-hash-tables', link: '/algorithm/hashing-and-hash-tables' },
            { text: 'dynamic-programming', link: '/algorithm/dynamic-programming' },
            { text: 'fibonacci-sequence-with-dp', link: '/algorithm/fibonacci-sequence-with-dp' },
            { text: 'longest-common-subsequence', link: '/algorithm/longest-common-subsequence' },
            { text: 'greedy-algorithms', link: '/algorithm/greedy-algorithms' },
            { text: 'knapsack-problem', link: '/algorithm/knapsack-problem' },
            { text: 'graph-algorithms', link: '/algorithm/graph-algorithms' },
            { text: 'backtracking-algorithms', link: '/algorithm/backtracking-algorithms' },
            { text: 'network-flow-algorithms', link: '/algorithm/network-flow-algorithms' },
            { text: 'string-matching-algorithms', link: '/algorithm/string-matching-algorithms' },
            { text: 'advanced-greedy-algorithms', link: '/algorithm/advanced-greedy-algorithms' },
          ],
          '/aws/': AWS.EN                       
        }
      }
    },
    th: {
      label: 'ภาษาไทย',
      lang: 'th-TH',
      link: '/th/',
      themeConfig: {
        sidebar: {
          '/th/git-&-github/': GitAndGitHub.TH,
          '/th/linux/': [
            { text: 'introduction-to-linux', link: '/th/linux/introduction-to-linux' },
            { text: 'basic-linux-commands', link: '/th/linux/basic-linux-commands' },
            { text: 'file-system-structure-and-permissions', link: '/th/linux/file-system-structure-and-permissions' },
            { text: 'user-management-and-groups', link: '/th/linux/user-management-and-groups' },
            { text: 'package-management', link: '/th/linux/package-management' },
            { text: 'advanced-file-permissions-and-access-control', link: '/th/linux/advanced-file-permissions-and-access-control' },
            { text: 'file-search', link: '/th/linux/file-search' },
            { text: 'file-compression-and-archiving', link: '/th/linux/file-compression-and-archiving' },
            { text: 'disk-management', link: '/th/linux/disk-management' },
            { text: 'backup-and-restore-data', link: '/th/linux/backup-and-restore-data' },
            { text: 'process-management', link: '/th/linux/process-management' },
            { text: 'system-services', link: '/th/linux/system-services' },
            { text: 'process-scheduling', link: '/th/linux/process-scheduling' },
            { text: 'cron', link: '/th/linux/cron' },
            { text: 'logs-and-system-monitoring', link: '/th/linux/logs-and-system-monitoring' },
            { text: 'managing-services', link: '/th/linux/managing-services' },
            { text: 'network-configuration', link: '/th/linux/network-configuration' },
            { text: 'firewall-configuration', link: '/th/linux/firewall-configuration' },
            { text: 'secure-ssh-access', link: '/th/linux/secure-ssh-access' },
            { text: 'file-encryption-and-secure-file-transfer', link: '/th/linux/file-encryption-and-secure-file-transfer' },
            { text: 'security-best-practices', link: '/th/linux/security-best-practices' },
            { text: 'performance-tuning', link: '/th/linux/performance-tuning' },
            { text: 'using-docker-with-linux', link: '/th/linux/using-docker-with-linux' },
            { text: 'virtualization-with-kvm', link: '/th/linux/virtualization-with-kvm' },
            { text: 'linux-kernel-compilation', link: '/th/linux/linux-kernel-compilation' },
            { text: 'system-monitoring-and-automation', link: '/th/linux/system-monitoring-and-automation' },
          ],
          '/th/docker/': [
            { text: 'introduction-to-docker', link: '/th/docker/introduction-to-docker' },
            { text: 'docker-architecture', link: '/th/docker/docker-architecture' },
            { text: 'docker-cli-basics', link: '/th/docker/docker-cli-basics' },
            { text: 'dockerfile-basics', link: '/th/docker/dockerfile-basics' },
            { text: 'creating-and-running-containers', link: '/th/docker/creating-and-running-containers' },
            { text: 'inspecting-containers', link: '/th/docker/inspecting-containers' },
            { text: 'working-with-images', link: '/th/docker/working-with-images' },
            { text: 'building-images', link: '/th/docker/building-images' },
            { text: 'volumes-and-persistent-storage', link: '/th/docker/volumes-and-persistent-storage' },
            { text: 'networking-basics', link: '/th/docker/networking-basics' },
            { text: 'exposing-ports', link: '/th/docker/exposing-ports' },
            { text: 'environment-variables', link: '/th/docker/environment-variables' },
            { text: 'introduction-to-docker-compose', link: '/th/docker/introduction-to-docker-compose' },
            { text: 'multi-container-applications', link: '/th/docker/multi-container-applications' },
            { text: 'managing-resources', link: '/th/docker/managing-resources' },
            { text: 'docker-compose-networking', link: '/th/docker/docker-compose-networking' },
            { text: 'docker-compose-volumes', link: '/th/docker/docker-compose-volumes' },
            { text: 'docker-compose-environment', link: '/th/docker/docker-compose-environment' },
            { text: 'optimizing-docker-images', link: '/th/docker/optimizing-docker-images' },
            { text: 'docker-registry', link: '/th/docker/docker-registry' },
            { text: 'docker-security', link: '/th/docker/docker-security' },
            { text: 'scaling-with-swarm', link: '/th/docker/scaling-with-swarm' },
          ],
          '/th/k8s/': [
            { text: 'introduction-to-kubernetes', link: '/th/k8s/introduction-to-kubernetes' },
            { text: 'kubernetes-architecture', link: '/th/k8s/kubernetes-architecture' },
            { text: 'kubernetes-architecture', link: '/th/k8s/kubernetes-architecture' },
            { text: 'installing-kubernetes', link: '/th/k8s/installing-kubernetes' },
            { text: 'kubectl-commands', link: '/th/k8s/kubectl-commands' },
            { text: 'pods', link: '/th/k8s/pods' },
            { text: 'deployments', link: '/th/k8s/deployments' },
            { text: 'replicasets', link: '/th/k8s/replicasets' },
            { text: 'services', link: '/th/k8s/services' },
            { text: 'configmaps', link: '/th/k8s/configmaps' },
            { text: 'secrets', link: '/th/k8s/secrets' },
            { text: 'volumes', link: '/th/k8s/volumes' },
            { text: 'persistent-volumes', link: '/th/k8s/persistent-volumes' },
            { text: 'namespaces', link: '/th/k8s/namespaces' },
            { text: 'resource-quotas', link: '/th/k8s/resource-quotas' },
            { text: 'scaling-applications', link: '/th/k8s/scaling-applications' },
            { text: 'networking-basics', link: '/th/k8s/networking-basics' },
            { text: 'monitoring-and-logging', link: '/th/k8s/monitoring-and-logging' },
            { text: 'ingress-controllers', link: '/th/k8s/ingress-controllers' },
            { text: 'statefulsets', link: '/th/k8s/statefulsets' },
            { text: 'daemonsets', link: '/th/k8s/daemonsets' },
            { text: 'jobs-and-cronjobs', link: '/th/k8s/jobs-and-cronjobs' },
            { text: 'advanced-deployments', link: '/th/k8s/advanced-deployments' },
            { text: 'custom-resource-definitions', link: '/th/k8s/custom-resource-definitions' },
            { text: 'scheduling', link: '/th/k8s/scheduling' },
            { text: 'security', link: '/th/k8s/security' },
            { text: 'deployment-patterns', link: '/th/k8s/deployment-patterns' },
            { text: 'backup-disaster-recovery', link: '/th/k8s/backup-disaster-recovery' },
            { text: 'multi-cluster-management', link: '/th/k8s/multi-cluster-management' },
            { text: 'helm', link: '/th/k8s/helm' },
          ],
          '/th/mongodb/': [
            { text: 'introduction-to-mongodb', link: '/th/mongodb/introduction-to-mongodb' },   
            { text: 'mongodb-architecture', link: '/th/mongodb/mongodb-architecture' }, 
            { text: 'database-and-collections', link: '/th/mongodb/database-and-collections' }, 
            { text: 'documents-and-bson', link: '/th/mongodb/documents-and-bson' }, 
            { text: 'basic-crud-operations', link: '/th/mongodb/basic-crud-operations' },
            { text: 'query-operators', link: '/th/mongodb/query-operators' },
            { text: 'mongodb-shell', link: '/th/mongodb/mongodb-shell' },
            { text: 'data-types', link: '/th/mongodb/data-types' },
            { text: 'indexes', link: '/th/mongodb/indexes' },
            { text: 'query-basics', link: '/th/mongodb/query-basics' },
            { text: 'aggregation-framework', link: '/th/mongodb/aggregation-framework' },
            { text: 'relationships', link: '/th/mongodb/relationships' },
            { text: 'transactions', link: '/th/mongodb/transactions' },
            { text: 'backup-and-restore', link: '/th/mongodb/backup-and-restore' },
            { text: 'schema-design', link: '/th/mongodb/schema-design' },
            { text: 'validation-rules', link: '/th/mongodb/validation-rules' },
            { text: 'replica-sets', link: '/th/mongodb/replica-sets' },
            { text: 'sharding', link: '/th/mongodb/sharding' },
            { text: 'performance-tuning', link: '/th/mongodb/performance-tuning' },
            { text: 'security', link: '/th/mongodb/security' },
            { text: 'advanced-aggregations', link: '/th/mongodb/advanced-aggregations' },
            { text: 'common-errors-debugging', link: '/th/mongodb/common-errors-debugging' },
          ],
          '/th/postgresql/': [
            { text: 'introduction-to-postgresql', link: '/th/postgresql/introduction-to-postgresql' },
            { text: 'postgresql-architecture', link: '/th/postgresql/postgresql-architecture' },
            { text: 'rdbms-concepts', link: '/th/postgresql/rdbms-concepts' },
            { text: 'object-model', link: '/th/postgresql/object-model' },
            { text: 'relational-model', link: '/th/postgresql/relational-model' },
            { text: 'high-level-database-concepts', link: '/th/postgresql/high-level-database-concepts' },
            { text: 'postgresql-tools', link: '/th/postgresql/postgresql-tools' },
            { text: 'basic-sql-commands', link: '/th/postgresql/basic-sql-commands' },
            { text: 'sorting-and-limiting', link: '/th/postgresql/sorting-and-limiting' },
            { text: 'basic-functions', link: '/th/postgresql/basic-functions' },
            { text: 'data-types', link: '/th/postgresql/data-types' },
            { text: 'constraints-and-keys', link: '/th/postgresql/constraints-and-keys' },
            { text: 'joins', link: '/th/postgresql/joins' },
            { text: 'aggregations', link: '/th/postgresql/aggregations' },
            { text: 'views', link: '/th/postgresql/views' },
            { text: 'indexing', link: '/th/postgresql/indexing' },
            { text: 'subqueries', link: '/th/postgresql/subqueries' },
            { text: 'stored-procedures', link: '/th/postgresql/stored-procedures' },
            { text: 'common-table-expressions', link: '/th/postgresql/common-table-expressions' },
            { text: 'transactions-and-acid-properties', link: '/th/postgresql/transactions-and-acid-properties' },
            { text: 'triggers', link: '/th/postgresql/triggers' },
            { text: 'json-and-jsonb', link: '/th/postgresql/json-and-jsonb' },
            { text: 'user-management', link: '/th/postgresql/user-management' },
            { text: 'backup-and-restore', link: '/th/postgresql/backup-and-restore' },
            { text: 'error-handling', link: '/th/postgresql/error-handling' },
            { text: 'authentication', link: '/th/postgresql/authentication' },
            { text: 'advanced-queries', link: '/th/postgresql/advanced-queries' },
            { text: 'data-security', link: '/th/postgresql/data-security' },
            { text: 'performance-optimization', link: '/th/postgresql/performance-optimization' },
            { text: 'replication', link: '/th/postgresql/replication' },
            { text: 'scaling', link: '/th/postgresql/scaling' },
          ],
          '/th/redis/': [
            { text: 'introduction-to-redis', link: '/th/redis/introduction-to-redis' },
            { text: 'in-memory-data-structure-store', link: '/th/redis/in-memory-data-structure-store' },
            { text: 'key-value-database', link: '/th/redis/key-value-database' },
            { text: 'cache', link: '/th/redis/cache' },
            { text: 'real-time-analytics', link: '/th/redis/real-time-analytics' },
            { text: 'session-management', link: '/th/redis/session-management' },
            { text: 'pub-sub-messaging', link: '/th/redis/pub-sub-messaging' },
            { text: 'leaderboards-and-counters', link: '/th/redis/leaderboards-and-counters' },
            { text: 'data-persistence-options', link: '/th/redis/data-persistence-options' },
            { text: 'rich-data-structures', link: '/th/redis/rich-data-structures' },
            { text: 'high-performance-and-scalability', link: '/th/redis/high-performance-and-scalability' },
            { text: 'redis-vs-sql-nosql-dbs', link: '/th/redis/redis-vs-sql-nosql-dbs' },
            { text: 'when-to-choose-redis', link: '/th/redis/when-to-choose-redis' },
            { text: 'using-package-managers', link: '/th/redis/using-package-managers' },
            { text: 'pre-compiled-binaries', link: '/th/redis/pre-compiled-binaries' },
            { text: 'using-docker', link: '/th/redis/using-docker' },
            { text: 'starting-the-server', link: '/th/redis/starting-the-server' },
            { text: 'connecting-using-redis-cli', link: '/th/redis/connecting-using-redis-cli' },
            { text: 'basic-commands-set-get', link: '/th/redis/basic-commands-set-get' },
            { text: 'del', link: '/th/redis/del' },
            { text: 'expire', link: '/th/redis/expire' },
            { text: 'ttl', link: '/th/redis/ttl' },
            { text: 'overview-of-data-types', link: '/th/redis/overview-of-data-types' },
            { text: 'strings', link: '/th/redis/strings' },
            { text: 'lists', link: '/th/redis/lists' },
            { text: 'sets', link: '/th/redis/sets' },
            { text: 'hashes', link: '/th/redis/hashes' },
            { text: 'sorted-sets', link: '/th/redis/sorted-sets' },
            { text: 'naming-conventions', link: '/th/redis/naming-conventions' },
            { text: 'retrieval-by-pattern', link: '/th/redis/retrieval-by-pattern' },
            { text: 'expiration', link: '/th/redis/expiration' },
            { text: 'atomicity-in-redis', link: '/th/redis/atomicity-in-redis' },
            { text: 'pipelining', link: '/th/redis/pipelining' },
            { text: 'batch-operations', link: '/th/redis/batch-operations' },
            { text: 'bitmaps', link: '/th/redis/bitmaps' },
            { text: 'hyperloglog', link: '/th/redis/hyperloglog' },
            { text: 'streams', link: '/th/redis/streams' },
            { text: 'geospatial-indexes', link: '/th/redis/geospatial-indexes' },
            { text: 'pub-sub', link: '/th/redis/pub-sub' },
            { text: 'transactions', link: '/th/redis/transactions' },
            { text: 'lua-scripting', link: '/th/redis/lua-scripting' },
            { text: 'persistence-options', link: '/th/redis/persistence-options' },
            { text: 'replication-basics', link: '/th/redis/replication-basics' },
            { text: 'sentinel', link: '/th/redis/sentinel' },
            { text: 'clustering', link: '/th/redis/clustering' },
            { text: 'ssl-tls-encryption', link: '/th/redis/ssl-tls-encryption' },
            { text: 'network-security', link: '/th/redis/network-security' },
            { text: 'authentication', link: '/th/redis/authentication' },
            { text: 'monitoring-and-optimization', link: '/th/redis/monitoring-and-optimization' },
            { text: 'modules', link: '/th/redis/modules' },
            { text: 'backup-and-recovery', link: '/th/redis/backup-and-recovery' },
            { text: 'upgrading-redis', link: '/th/redis/upgrading-redis' },
            { text: 'disaster-recovery', link: '/th/redis/disaster-recovery' },
          ],
          '/th/algorithm/': [
            { text: 'introduction-to-algorithms', link: '/th/algorithm/introduction-to-algorithms' },
            { text: 'time-and-space-complexity', link: '/th/algorithm/time-and-space-complexity' },
            { text: 'asymptotic-notations', link: '/th/algorithm/asymptotic-notations' },
            { text: 'arrays', link: '/th/algorithm/arrays' },
            { text: 'string', link: '/th/algorithm/string' },
            { text: 'linked-list', link: '/th/algorithm/linked-list' },
            { text: 'stacks-and-queues', link: '/th/algorithm/stacks-and-queues' },
            { text: 'recursion-and-divide-and-conquer-algorithms', link: '/th/algorithm/recursion-and-divide-and-conquer-algorithms' },
            { text: 'linear-search-and-binary-search', link: '/th/algorithm/linear-search-and-binary-search' },
            { text: 'sorting-algorithms', link: '/th/algorithm/sorting-algorithms' },
            { text: 'merge-sort-and-quick-sort', link: '/th/algorithm/merge-sort-and-quick-sort' },
            { text: 'heaps-and-priority-queues', link: '/th/algorithm/heaps-and-priority-queues' },
            { text: 'hashing-and-hash-tables', link: '/th/algorithm/hashing-and-hash-tables' },
            { text: 'dynamic-programming', link: '/th/algorithm/dynamic-programming' },
            { text: 'fibonacci-sequence-with-dp', link: '/th/algorithm/fibonacci-sequence-with-dp' },
            { text: 'longest-common-subsequence', link: '/th/algorithm/longest-common-subsequence' },
            { text: 'greedy-algorithms', link: '/th/algorithm/greedy-algorithms' },
            { text: 'knapsack-problem', link: '/th/algorithm/knapsack-problem' },
            { text: 'graph-algorithms', link: '/th/algorithm/graph-algorithms' },
            { text: 'backtracking-algorithms', link: '/th/algorithm/backtracking-algorithms' },
            { text: 'network-flow-algorithms', link: '/th/algorithm/network-flow-algorithms' },
            { text: 'string-matching-algorithms', link: '/th/algorithm/string-matching-algorithms' },
            { text: 'advanced-greedy-algorithms', link: '/th/algorithm/advanced-greedy-algorithms' },
          ],
          '/th/aws/': AWS.TH       
        }
      }
    }
  }
})
