import { defineConfig } from 'vitepress'

// https://vitepress.dev/reference/site-config
export default defineConfig({
  title: "JN-Trail-Compass",
  description: "A VitePress Site",
  themeConfig: {
    // https://vitepress.dev/reference/default-theme-config
    socialLinks: [
      { icon: 'github', link: 'https://github.com/vuejs/vitepress' }
    ]
  },
  base: '/jn-trail-compass/',
  locales: {
    root: {
      label: 'English',
      lang: 'en',
      link: '/',
      themeConfig: {
        sidebar: {
          '/git-&-github/': [
            { text: 'introduction-to-git', link: '/git-&-github/introduction-to-git' },
            { text: 'repository-initialization', link: '/git-&-github/repository-initialization' },
            { text: 'git-status-&-staging-area', link: '/git-&-github/git-status-&-staging-area' },
            { text: 'git-commit-&-history', link: '/git-&-github/git-commit-&-history' },
            { text: 'git-branching', link: '/git-&-github/git-branching' },
            { text: 'git-merging', link: '/git-&-github/git-merging' },
            { text: 'git-merging', link: '/git-&-github/git-merging' },
            { text: 'handling-merge-conflicts', link: '/git-&-github/handling-merge-conflicts' },
            { text: 'handling-merge-conflicts', link: '/git-&-github/handling-merge-conflicts' },
            { text: 'git-rebase', link: '/git-&-github/git-rebase' },
            { text: 'git-reset-checkout', link: '/git-&-github/git-reset-checkout' },
            { text: 'git-stash', link: '/git-&-github/git-stash' },
            { text: 'introduction-to-github', link: '/git-&-github/introduction-to-github' },
            { text: 'pushing-to-github', link: '/git-&-github/pushing-to-github' },
            { text: 'pull-requests', link: '/git-&-github/pull-requests' },
            { text: 'collaborating-with-teams', link: '/git-&-github/collaborating-with-teams' },
            { text: 'github-actions', link: '/git-&-github/github-actions' },
            { text: 'git-submodules', link: '/git-&-github/git-submodules' },
            { text: 'git-tags', link: '/git-&-github/git-tags' },
            { text: 'git-hooks', link: '/git-&-github/git-hooks' },
            { text: 'cherry-picking-changes', link: '/git-&-github/cherry-picking-changes' },
            { text: 'git-bisect', link: '/git-&-github/git-bisect' },
            { text: 'git-with-large-project', link: '/git-&-github/git-with-large-project' },
            { text: 'git-with-ci-cd', link: '/git-&-github/git-with-ci-cd' },
            { text: 'reverting-changes-and-handling-history', link: '/git-&-github/reverting-changes-and-handling-history' },
            { text: 'git-workflow-for-teams', link: '/git-&-github/git-workflow-for-teams' },
            { text: 'handling-multiple-remotes', link: '/git-&-github/handling-multiple-remotes' },
          ],
          '/linux/': [
            { text: 'introduction-to-linux', link: '/linux/introduction-to-linux' },
            { text: 'basic-linux-commands', link: '/linux/basic-linux-commands' },
            { text: 'file-system-structure-and-permissions', link: '/linux/file-system-structure-and-permissions' },
            { text: 'user-management-and-groups', link: '/linux/user-management-and-groups' },
            { text: 'package-management', link: '/linux/package-management' },
            { text: 'advanced-file-permissions-and-access-control', link: '/linux/advanced-file-permissions-and-access-control' },
            { text: 'file-search', link: '/linux/file-search' },
            { text: 'file-compression-and-archiving', link: '/linux/file-compression-and-archiving' },
            { text: 'disk-management', link: '/linux/disk-management' },
            { text: 'backup-and-restore-data', link: '/linux/backup-and-restore-data' },
            { text: 'process-management', link: '/linux/process-management' },
            { text: 'system-services', link: '/linux/system-services' },
            { text: 'process-scheduling', link: '/linux/process-scheduling' },
            { text: 'cron', link: '/linux/cron' },
            { text: 'logs-and-system-monitoring', link: '/linux/logs-and-system-monitoring' },
            { text: 'managing-services', link: '/linux/managing-services' },
            { text: 'network-configuration', link: '/linux/network-configuration' },
            { text: 'firewall-configuration', link: '/linux/firewall-configuration' },
            { text: 'secure-ssh-access', link: '/linux/secure-ssh-access' },
            { text: 'file-encryption-and-secure-file-transfer', link: '/linux/file-encryption-and-secure-file-transfer' },
            { text: 'security-best-practices', link: '/linux/security-best-practices' },
            { text: 'performance-tuning', link: '/linux/performance-tuning' },
            { text: 'using-docker-with-linux', link: '/linux/using-docker-with-linux' },
            { text: 'virtualization-with-kvm', link: '/linux/virtualization-with-kvm' },
            { text: 'linux-kernel-compilation', link: '/linux/linux-kernel-compilation' },
            { text: 'system-monitoring-and-automation', link: '/linux/system-monitoring-and-automation' },
          ],
          '/docker/': [
            { text: 'introduction-to-docker', link: '/docker/introduction-to-docker' },
            { text: 'docker-architecture', link: '/docker/docker-architecture' },
            { text: 'docker-cli-basics', link: '/docker/docker-cli-basics' },
            { text: 'dockerfile-basics', link: '/docker/dockerfile-basics' },
            { text: 'creating-and-running-containers', link: '/docker/creating-and-running-containers' },
            { text: 'inspecting-containers', link: '/docker/inspecting-containers' },
            { text: 'working-with-images', link: '/docker/working-with-images' },
            { text: 'building-images', link: '/docker/building-images' },
            { text: 'volumes-and-persistent-storage', link: '/docker/volumes-and-persistent-storage' },
            { text: 'networking-basics', link: '/docker/networking-basics' },
            { text: 'exposing-ports', link: '/docker/exposing-ports' },
            { text: 'environment-variables', link: '/docker/environment-variables' },
            { text: 'introduction-to-docker-compose', link: '/docker/introduction-to-docker-compose' },
            { text: 'multi-container-applications', link: '/docker/multi-container-applications' },
            { text: 'managing-resources', link: '/docker/managing-resources' },
            { text: 'docker-compose-networking', link: '/docker/docker-compose-networking' },
            { text: 'docker-compose-volumes', link: '/docker/docker-compose-volumes' },
            { text: 'docker-compose-environment', link: '/docker/docker-compose-environment' },
            { text: 'optimizing-docker-images', link: '/docker/optimizing-docker-images' },
            { text: 'docker-registry', link: '/docker/docker-registry' },
            { text: 'docker-security', link: '/docker/docker-security' },
            { text: 'scaling-with-swarm', link: '/docker/scaling-with-swarm' },
          ],
          '/k8s/': [
            { text: 'introduction-to-kubernetes', link: '/k8s/introduction-to-kubernetes' },
            { text: 'kubernetes-architecture', link: '/k8s/kubernetes-architecture' },
            { text: 'kubernetes-architecture', link: '/k8s/kubernetes-architecture' },
            { text: 'installing-kubernetes', link: '/k8s/installing-kubernetes' },
            { text: 'kubectl-commands', link: '/k8s/kubectl-commands' },
            { text: 'pods', link: '/k8s/pods' },
            { text: 'deployments', link: '/k8s/deployments' },
            { text: 'replicasets', link: '/k8s/replicasets' },
            { text: 'services', link: '/k8s/services' },
            { text: 'configmaps', link: '/k8s/configmaps' },
            { text: 'secrets', link: '/k8s/secrets' },
            { text: 'volumes', link: '/k8s/volumes' },
            { text: 'persistent-volumes', link: '/k8s/persistent-volumes' },
            { text: 'namespaces', link: '/k8s/namespaces' },
            { text: 'resource-quotas', link: '/k8s/resource-quotas' },
            { text: 'scaling-applications', link: '/k8s/scaling-applications' },
            { text: 'networking-basics', link: '/k8s/networking-basics' },
            { text: 'monitoring-and-logging', link: '/k8s/monitoring-and-logging' },
            { text: 'ingress-controllers', link: '/k8s/ingress-controllers' },
            { text: 'statefulsets', link: '/k8s/statefulsets' },
            { text: 'daemonsets', link: '/k8s/daemonsets' },
            { text: 'jobs-and-cronjobs', link: '/k8s/jobs-and-cronjobs' },
            { text: 'advanced-deployments', link: '/k8s/advanced-deployments' },
            { text: 'custom-resource-definitions', link: '/k8s/custom-resource-definitions' },
            { text: 'scheduling', link: '/k8s/scheduling' },
            { text: 'security', link: '/k8s/security' },
            { text: 'deployment-patterns', link: '/k8s/deployment-patterns' },
            { text: 'backup-disaster-recovery', link: '/k8s/backup-disaster-recovery' },
            { text: 'multi-cluster-management', link: '/k8s/multi-cluster-management' },
            { text: 'helm', link: '/k8s/helm' },
          ],
          '/mongodb/': [
            { text: 'introduction-to-mongodb', link: '/mongodb/introduction-to-mongodb' },   
            { text: 'mongodb-architecture', link: '/mongodb/mongodb-architecture' }, 
            { text: 'database-and-collections', link: '/mongodb/database-and-collections' }, 
            { text: 'documents-and-bson', link: '/mongodb/documents-and-bson' }, 
            { text: 'basic-crud-operations', link: '/mongodb/basic-crud-operations' },
            { text: 'query-operators', link: '/mongodb/query-operators' },
            { text: 'mongodb-shell', link: '/mongodb/mongodb-shell' },
            { text: 'data-types', link: '/mongodb/data-types' },
            { text: 'indexes', link: '/mongodb/indexes' },
            { text: 'query-basics', link: '/mongodb/query-basics' },
            { text: 'aggregation-framework', link: '/mongodb/aggregation-framework' },
            { text: 'relationships', link: '/mongodb/relationships' },
            { text: 'transactions', link: '/mongodb/transactions' },
            { text: 'backup-and-restore', link: '/mongodb/backup-and-restore' },
            { text: 'schema-design', link: '/mongodb/schema-design' },
            { text: 'validation-rules', link: '/mongodb/validation-rules' },
            { text: 'replica-sets', link: '/mongodb/replica-sets' },
            { text: 'sharding', link: '/mongodb/sharding' },
            { text: 'performance-tuning', link: '/mongodb/performance-tuning' },
            { text: 'security', link: '/mongodb/security' },
            { text: 'advanced-aggregations', link: '/mongodb/advanced-aggregations' },
            { text: 'common-errors-debugging', link: '/mongodb/common-errors-debugging' },
          ],
          '/postgresql/': [
            { text: 'introduction-to-postgresql', link: '/postgresql/introduction-to-postgresql' },
            { text: 'postgresql-architecture', link: '/postgresql/postgresql-architecture' },
            { text: 'rdbms-concepts', link: '/postgresql/rdbms-concepts' },
            { text: 'object-model', link: '/postgresql/object-model' },
            { text: 'relational-model', link: '/postgresql/relational-model' },
            { text: 'high-level-database-concepts', link: '/postgresql/high-level-database-concepts' },
            { text: 'postgresql-tools', link: '/postgresql/postgresql-tools' },
            { text: 'basic-sql-commands', link: '/postgresql/basic-sql-commands' },
            { text: 'sorting-and-limiting', link: '/postgresql/sorting-and-limiting' },
            { text: 'basic-functions', link: '/postgresql/basic-functions' },
            { text: 'data-types', link: '/postgresql/data-types' },
            { text: 'constraints-and-keys', link: '/postgresql/constraints-and-keys' },
            { text: 'joins', link: '/postgresql/joins' },
            { text: 'aggregations', link: '/postgresql/aggregations' },
            { text: 'views', link: '/postgresql/views' },
            { text: 'indexing', link: '/postgresql/indexing' },
            { text: 'subqueries', link: '/postgresql/subqueries' },
            { text: 'stored-procedures', link: '/postgresql/stored-procedures' },
            { text: 'common-table-expressions', link: '/postgresql/common-table-expressions' },
            { text: 'transactions-and-acid-properties', link: '/postgresql/transactions-and-acid-properties' },
            { text: 'triggers', link: '/postgresql/triggers' },
            { text: 'json-and-jsonb', link: '/postgresql/json-and-jsonb' },
            { text: 'user-management', link: '/postgresql/user-management' },
            { text: 'backup-and-restore', link: '/postgresql/backup-and-restore' },
            { text: 'error-handling', link: '/postgresql/error-handling' },
            { text: 'authentication', link: '/postgresql/authentication' },
            { text: 'advanced-queries', link: '/postgresql/advanced-queries' },
            { text: 'data-security', link: '/postgresql/data-security' },
            { text: 'performance-optimization', link: '/postgresql/performance-optimization' },
            { text: 'replication', link: '/postgresql/replication' },
            { text: 'scaling', link: '/postgresql/scaling' },
          ],
          '/redis/': [
            { text: 'introduction-to-redis', link: '/redis/introduction-to-redis' },
            { text: 'in-memory-data-structure-store', link: '/redis/in-memory-data-structure-store' },
            { text: 'key-value-database', link: '/redis/key-value-database' },
            { text: 'cache', link: '/redis/cache' },
            { text: 'real-time-analytics', link: '/redis/real-time-analytics' },
            { text: 'session-management', link: '/redis/session-management' },
            { text: 'pub-sub-messaging', link: '/redis/pub-sub-messaging' },
            { text: 'leaderboards-and-counters', link: '/redis/leaderboards-and-counters' },
            { text: 'data-persistence-options', link: '/redis/data-persistence-options' },
            { text: 'rich-data-structures', link: '/redis/rich-data-structures' },
            { text: 'high-performance-and-scalability', link: '/redis/high-performance-and-scalability' },
            { text: 'redis-vs-sql-nosql-dbs', link: '/redis/redis-vs-sql-nosql-dbs' },
            { text: 'when-to-choose-redis', link: '/redis/when-to-choose-redis' },
            { text: 'using-package-managers', link: '/redis/using-package-managers' },
            { text: 'pre-compiled-binaries', link: '/redis/pre-compiled-binaries' },
            { text: 'using-docker', link: '/redis/using-docker' },
            { text: 'starting-the-server', link: '/redis/starting-the-server' },
            { text: 'connecting-using-redis-cli', link: '/redis/connecting-using-redis-cli' },
            { text: 'basic-commands-set-get', link: '/redis/basic-commands-set-get' },
            { text: 'del', link: '/redis/del' },
            { text: 'expire', link: '/redis/expire' },
            { text: 'ttl', link: '/redis/ttl' },
            { text: 'overview-of-data-types', link: '/redis/overview-of-data-types' },
            { text: 'strings', link: '/redis/strings' },
            { text: 'lists', link: '/redis/lists' },
            { text: 'sets', link: '/redis/sets' },
            { text: 'hashes', link: '/redis/hashes' },
            { text: 'sorted-sets', link: '/redis/sorted-sets' },
            { text: 'naming-conventions', link: '/redis/naming-conventions' },
            { text: 'retrieval-by-pattern', link: '/redis/retrieval-by-pattern' },
            { text: 'expiration', link: '/redis/expiration' },
            { text: 'atomicity-in-redis', link: '/redis/atomicity-in-redis' },
            { text: 'pipelining', link: '/redis/pipelining' },
            { text: 'batch-operations', link: '/redis/batch-operations' },
            { text: 'bitmaps', link: '/redis/bitmaps' },
            { text: 'hyperloglog', link: '/redis/hyperloglog' },
            { text: 'streams', link: '/redis/streams' },
            { text: 'geospatial-indexes', link: '/redis/geospatial-indexes' },
            { text: 'pub-sub', link: '/redis/pub-sub' },
            { text: 'transactions', link: '/redis/transactions' },
            { text: 'lua-scripting', link: '/redis/lua-scripting' },
            { text: 'persistence-options', link: '/redis/persistence-options' },
            { text: 'replication-basics', link: '/redis/replication-basics' },
            { text: 'sentinel', link: '/redis/sentinel' },
            { text: 'clustering', link: '/redis/clustering' },
            { text: 'ssl-tls-encryption', link: '/redis/ssl-tls-encryption' },
            { text: 'network-security', link: '/redis/network-security' },
            { text: 'authentication', link: '/redis/authentication' },
            { text: 'monitoring-and-optimization', link: '/redis/monitoring-and-optimization' },
            { text: 'modules', link: '/redis/modules' },
            { text: 'backup-and-recovery', link: '/redis/backup-and-recovery' },
            { text: 'upgrading-redis', link: '/redis/upgrading-redis' },
            { text: 'disaster-recovery', link: '/redis/disaster-recovery' },
          ],
          '/algorithm/': [
            { text: 'introduction-to-algorithms', link: '/algorithm/introduction-to-algorithms' },
            { text: 'time-and-space-complexity', link: '/algorithm/time-and-space-complexity' },
            { text: 'asymptotic-notations', link: '/algorithm/asymptotic-notations' },
            { text: 'arrays', link: '/algorithm/arrays' },
            { text: 'string', link: '/algorithm/string' },
            { text: 'linked-list', link: '/algorithm/linked-list' },
            { text: 'stacks-and-queues', link: '/algorithm/stacks-and-queues' },
            { text: 'recursion-and-divide-and-conquer-algorithms', link: '/algorithm/recursion-and-divide-and-conquer-algorithms' },
            { text: 'linear-search-and-binary-search', link: '/algorithm/linear-search-and-binary-search' },
            { text: 'sorting-algorithms', link: '/algorithm/sorting-algorithms' },
            { text: 'merge-sort-and-quick-sort', link: '/algorithm/merge-sort-and-quick-sort' },
            { text: 'heaps-and-priority-queues', link: '/algorithm/heaps-and-priority-queues' },
            { text: 'hashing-and-hash-tables', link: '/algorithm/hashing-and-hash-tables' },
            { text: 'dynamic-programming', link: '/algorithm/dynamic-programming' },
            { text: 'fibonacci-sequence-with-dp', link: '/algorithm/fibonacci-sequence-with-dp' },
            { text: 'longest-common-subsequence', link: '/algorithm/longest-common-subsequence' },
            { text: 'greedy-algorithms', link: '/algorithm/greedy-algorithms' },
            { text: 'knapsack-problem', link: '/algorithm/knapsack-problem' },
            { text: 'graph-algorithms', link: '/algorithm/graph-algorithms' },
            { text: 'backtracking-algorithms', link: '/algorithm/backtracking-algorithms' },
            { text: 'network-flow-algorithms', link: '/algorithm/network-flow-algorithms' },
            { text: 'string-matching-algorithms', link: '/algorithm/string-matching-algorithms' },
            { text: 'advanced-greedy-algorithms', link: '/algorithm/advanced-greedy-algorithms' },
          ],
          '/aws/': [
            { text: 'introduction-to-aws', link: '/aws/introduction-to-aws' },
            {
              text: 'Compute',
              collapsed: true,
              items: [
                { text: 'Compute', link: '/aws/compute/compute' },
                { text: 'EC2', link: '/aws/compute/ec2' },
                { text: 'Lightsail', link: '/aws/compute/lightsail' },
                { text: 'Elastic Beanstalk', link: '/aws/compute/elastic-beanstalk' },
                { text: 'App Runner', link: '/aws/compute/app-runner' },
                { text: 'Batch', link: '/aws/compute/batch' },
                { text: 'Serverless', link: '/aws/compute/serverless' },
                { text: 'Lambda', link: '/aws/compute/lambda' },
                { text: 'EC2 Image Builder', link: '/aws/compute/ec2-image-builder' },
                { text: 'AWS Outposts', link: '/aws/compute/aws-outposts' },
                { text: 'AWS Wavelength', link: '/aws/compute/aws-wavelength' }
              ]
            },
            {
              text: 'Containers',
              collapsed: true,
              items: [
                { text: 'Containers', link: '/aws/containers/containers' },
                { text: 'Elastic Container Service', link: '/aws/containers/elastic-container-service' },
                { text: 'Elastic Kubernetes Service', link: '/aws/containers/elastic-kubernetes-service' },
                { text: 'Fargate', link: '/aws/containers/fargate' }
              ]
            },
            {
              text: 'Storage',
              collapsed: true,
              items: [
                { text: 'Storage', link: '/aws/storage/storage' },
                { text: 'S3', link: '/aws/storage/s3' },
                { text: 'Elastic File System', link: '/aws/storage/elastic-file-system' },
                { text: 'FSx', link: '/aws/storage/fsx' },
                { text: 'S3 Glacier', link: '/aws/storage/s3-glacier' },
                { text: 'Storage Gateway', link: '/aws/storage/storage-gateway' },
                { text: 'Backup', link: '/aws/storage/backup' }
              ]
            },
            {
              text: 'Database',
              collapsed: true,
              items: [
                { text: 'Database', link: '/aws/database/database' },
                { text: 'RDS', link: '/aws/database/rds' },
                { text: 'Aurora', link: '/aws/database/aurora' },
                { text: 'Redshift', link: '/aws/database/redshift' },
                { text: 'DynamoDB', link: '/aws/database/dynamodb' },
                { text: 'DocumentDB', link: '/aws/database/documentdb' },
                { text: 'Keyspaces', link: '/aws/database/keyspaces' },
                { text: 'Timestream', link: '/aws/database/timestream' },
                { text: 'Quantum Ledger Database', link: '/aws/database/quantum-ledger-database' },
                { text: 'ElastiCache', link: '/aws/database/elasticache' },
                { text: 'Neptune', link: '/aws/database/neptune' },
                { text: 'Database Migration Service', link: '/aws/database/database-migration-service' }
              ]
            },
            {
              text: 'Networking & Content Delivery',
              collapsed: true,
              items: [
                { text: 'Networking & Content Delivery', link: '/aws/networking/networking' },
                { text: 'VPC', link: '/aws/networking/vpc' },
                { text: 'CloudFront', link: '/aws/networking/cloudfront' },
                { text: 'Route 53', link: '/aws/networking/route-53' },
                { text: 'API Gateway', link: '/aws/networking/api-gateway' },
                { text: 'Global Accelerator', link: '/aws/networking/global-accelerator' },
                { text: 'Direct Connect', link: '/aws/networking/direct-connect' },
                { text: 'PrivateLink', link: '/aws/networking/privatelink' },
                { text: 'App Mesh', link: '/aws/networking/app-mesh' },
                { text: 'Cloud Map', link: '/aws/networking/cloud-map' }
              ]
            },
            {
              text: 'Developer Tools',
              collapsed: true,
              items: [
                { text: 'Developer Tools', link: '/aws/developer-tools/developer-tools' },
                { text: 'Cloud9', link: '/aws/developer-tools/cloud9' },
                { text: 'CloudShell', link: '/aws/developer-tools/cloudshell' },
                { text: 'CodeBuild', link: '/aws/developer-tools/codebuild' },
                { text: 'CodeCommit', link: '/aws/developer-tools/codecommit' },
                { text: 'CodeDeploy', link: '/aws/developer-tools/codedeploy' },
                { text: 'CodePipeline', link: '/aws/developer-tools/codepipeline' },
                { text: 'X-Ray', link: '/aws/developer-tools/x-ray' },
                { text: 'Tools & SDKs', link: '/aws/developer-tools/tools-and-sdks' }
              ]
            },
            {
              text: 'Management & Governance',
              collapsed: true,
              items: [
                { text: 'Management & Governance', link: '/aws/management/management-and-governance' },
                { text: 'Auto Scaling', link: '/aws/management/auto-scaling' },
                { text: 'CloudFormation', link: '/aws/management/cloudformation' },
                { text: 'CloudTrail', link: '/aws/management/cloudtrail' },
                { text: 'CloudWatch', link: '/aws/management/cloudwatch' },
                { text: 'Config', link: '/aws/management/config' },
                { text: 'Control Tower', link: '/aws/management/control-tower' },
                { text: 'License Manager', link: '/aws/management/license-manager' },
                { text: 'OpsWorks', link: '/aws/management/opsworks' },
                { text: 'Personal Health Dashboard', link: '/aws/management/personal-health-dashboard' },
                { text: 'Service Catalog', link: '/aws/management/service-catalog' },
                { text: 'Trusted Advisor', link: '/aws/management/trusted-advisor' },
                { text: 'Well-Architected Tool', link: '/aws/management/well-architected-tool' }
              ]
            },
            {
              text: 'Security, Identity, & Compliance',
              collapsed: true,
              items: [
                { text: 'Security, Identity, & Compliance', link: '/aws/security/security-identity-compliance' },
                { text: 'IAM', link: '/aws/security/iam' },
                { text: 'Cognito', link: '/aws/security/cognito' },
                { text: 'Secrets Manager', link: '/aws/security/secrets-manager' },
                { text: 'KMS', link: '/aws/security/kms' },
                { text: 'Artifact', link: '/aws/security/artifact' },
                { text: 'Shield', link: '/aws/security/shield' },
                { text: 'WAF', link: '/aws/security/waf' },
                { text: 'Security Hub', link: '/aws/security/security-hub' },
                { text: 'GuardDuty', link: '/aws/security/guardduty' },
                { text: 'Inspector', link: '/aws/security/inspector' },
                { text: 'Macie', link: '/aws/security/macie' },
                { text: 'Detective', link: '/aws/security/detective' },
                { text: 'Audit Manager', link: '/aws/security/audit-manager' },
                { text: 'Certificate Manager', link: '/aws/security/certificate-manager' }
              ]
            }
          ]                       
        }
      }
    },
    th: {
      label: 'ภาษาไทย',
      lang: 'th-TH',
      link: '/th/',
      themeConfig: {
        sidebar: {
          '/th/git-&-github/': [
            { text: 'introduction-to-git', link: '/th/git-&-github/introduction-to-git' },
            { text: 'repository-initialization', link: '/th/git-&-github/repository-initialization' },
            { text: 'git-status-&-staging-area', link: '/th/git-&-github/git-status-&-staging-area' },
            { text: 'git-commit-&-history', link: '/th/git-&-github/git-commit-&-history' },
            { text: 'git-branching', link: '/th/git-&-github/git-branching' },
            { text: 'git-merging', link: '/th/git-&-github/git-merging' },
            { text: 'handling-merge-conflicts', link: '/th/git-&-github/handling-merge-conflicts' },
            { text: 'git-rebase', link: '/th/git-&-github/git-rebase' },
            { text: 'git-reset-checkout', link: '/th/git-&-github/git-reset-checkout' },
            { text: 'git-stash', link: '/th/git-&-github/git-stash' },
            { text: 'introduction-to-github', link: '/th/git-&-github/introduction-to-github' },
            { text: 'pushing-to-github', link: '/th/git-&-github/pushing-to-github' },
            { text: 'pull-requests', link: '/th/git-&-github/pull-requests' },
            { text: 'collaborating-with-teams', link: '/th/git-&-github/collaborating-with-teams' },
            { text: 'github-actions', link: '/th/git-&-github/github-actions' },
            { text: 'git-submodules', link: '/th/git-&-github/git-submodules' },
            { text: 'git-tags', link: '/th/git-&-github/git-tags' },
            { text: 'git-hooks', link: '/th/git-&-github/git-hooks' },
            { text: 'cherry-picking-changes', link: '/th/git-&-github/cherry-picking-changes' },
            { text: 'git-bisect', link: '/th/git-&-github/git-bisect' },
            { text: 'git-with-large-project', link: '/th/git-&-github/git-with-large-project' },
            { text: 'git-with-ci-cd', link: '/th/git-&-github/git-with-ci-cd' },
            { text: 'reverting-changes-and-handling-history', link: '/th/git-&-github/reverting-changes-and-handling-history' },
            { text: 'git-workflow-for-teams', link: '/th/git-&-github/git-workflow-for-teams' },
            { text: 'handling-multiple-remotes', link: '/th/git-&-github/handling-multiple-remotes' },
          ],
          '/th/linux/': [
            { text: 'introduction-to-linux', link: '/th/linux/introduction-to-linux' },
            { text: 'basic-linux-commands', link: '/th/linux/basic-linux-commands' },
            { text: 'file-system-structure-and-permissions', link: '/th/linux/file-system-structure-and-permissions' },
            { text: 'user-management-and-groups', link: '/th/linux/user-management-and-groups' },
            { text: 'package-management', link: '/th/linux/package-management' },
            { text: 'advanced-file-permissions-and-access-control', link: '/th/linux/advanced-file-permissions-and-access-control' },
            { text: 'file-search', link: '/th/linux/file-search' },
            { text: 'file-compression-and-archiving', link: '/th/linux/file-compression-and-archiving' },
            { text: 'disk-management', link: '/th/linux/disk-management' },
            { text: 'backup-and-restore-data', link: '/th/linux/backup-and-restore-data' },
            { text: 'process-management', link: '/th/linux/process-management' },
            { text: 'system-services', link: '/th/linux/system-services' },
            { text: 'process-scheduling', link: '/th/linux/process-scheduling' },
            { text: 'cron', link: '/th/linux/cron' },
            { text: 'logs-and-system-monitoring', link: '/th/linux/logs-and-system-monitoring' },
            { text: 'managing-services', link: '/th/linux/managing-services' },
            { text: 'network-configuration', link: '/th/linux/network-configuration' },
            { text: 'firewall-configuration', link: '/th/linux/firewall-configuration' },
            { text: 'secure-ssh-access', link: '/th/linux/secure-ssh-access' },
            { text: 'file-encryption-and-secure-file-transfer', link: '/th/linux/file-encryption-and-secure-file-transfer' },
            { text: 'security-best-practices', link: '/th/linux/security-best-practices' },
            { text: 'performance-tuning', link: '/th/linux/performance-tuning' },
            { text: 'using-docker-with-linux', link: '/th/linux/using-docker-with-linux' },
            { text: 'virtualization-with-kvm', link: '/th/linux/virtualization-with-kvm' },
            { text: 'linux-kernel-compilation', link: '/th/linux/linux-kernel-compilation' },
            { text: 'system-monitoring-and-automation', link: '/th/linux/system-monitoring-and-automation' },
          ],
          '/th/docker/': [
            { text: 'introduction-to-docker', link: '/th/docker/introduction-to-docker' },
            { text: 'docker-architecture', link: '/th/docker/docker-architecture' },
            { text: 'docker-cli-basics', link: '/th/docker/docker-cli-basics' },
            { text: 'dockerfile-basics', link: '/th/docker/dockerfile-basics' },
            { text: 'creating-and-running-containers', link: '/th/docker/creating-and-running-containers' },
            { text: 'inspecting-containers', link: '/th/docker/inspecting-containers' },
            { text: 'working-with-images', link: '/th/docker/working-with-images' },
            { text: 'building-images', link: '/th/docker/building-images' },
            { text: 'volumes-and-persistent-storage', link: '/th/docker/volumes-and-persistent-storage' },
            { text: 'networking-basics', link: '/th/docker/networking-basics' },
            { text: 'exposing-ports', link: '/th/docker/exposing-ports' },
            { text: 'environment-variables', link: '/th/docker/environment-variables' },
            { text: 'introduction-to-docker-compose', link: '/th/docker/introduction-to-docker-compose' },
            { text: 'multi-container-applications', link: '/th/docker/multi-container-applications' },
            { text: 'managing-resources', link: '/th/docker/managing-resources' },
            { text: 'docker-compose-networking', link: '/th/docker/docker-compose-networking' },
            { text: 'docker-compose-volumes', link: '/th/docker/docker-compose-volumes' },
            { text: 'docker-compose-environment', link: '/th/docker/docker-compose-environment' },
            { text: 'optimizing-docker-images', link: '/th/docker/optimizing-docker-images' },
            { text: 'docker-registry', link: '/th/docker/docker-registry' },
            { text: 'docker-security', link: '/th/docker/docker-security' },
            { text: 'scaling-with-swarm', link: '/th/docker/scaling-with-swarm' },
          ],
          '/th/k8s/': [
            { text: 'introduction-to-kubernetes', link: '/th/k8s/introduction-to-kubernetes' },
            { text: 'kubernetes-architecture', link: '/th/k8s/kubernetes-architecture' },
            { text: 'kubernetes-architecture', link: '/th/k8s/kubernetes-architecture' },
            { text: 'installing-kubernetes', link: '/th/k8s/installing-kubernetes' },
            { text: 'kubectl-commands', link: '/th/k8s/kubectl-commands' },
            { text: 'pods', link: '/th/k8s/pods' },
            { text: 'deployments', link: '/th/k8s/deployments' },
            { text: 'replicasets', link: '/th/k8s/replicasets' },
            { text: 'services', link: '/th/k8s/services' },
            { text: 'configmaps', link: '/th/k8s/configmaps' },
            { text: 'secrets', link: '/th/k8s/secrets' },
            { text: 'volumes', link: '/th/k8s/volumes' },
            { text: 'persistent-volumes', link: '/th/k8s/persistent-volumes' },
            { text: 'namespaces', link: '/th/k8s/namespaces' },
            { text: 'resource-quotas', link: '/th/k8s/resource-quotas' },
            { text: 'scaling-applications', link: '/th/k8s/scaling-applications' },
            { text: 'networking-basics', link: '/th/k8s/networking-basics' },
            { text: 'monitoring-and-logging', link: '/th/k8s/monitoring-and-logging' },
            { text: 'ingress-controllers', link: '/th/k8s/ingress-controllers' },
            { text: 'statefulsets', link: '/th/k8s/statefulsets' },
            { text: 'daemonsets', link: '/th/k8s/daemonsets' },
            { text: 'jobs-and-cronjobs', link: '/th/k8s/jobs-and-cronjobs' },
            { text: 'advanced-deployments', link: '/th/k8s/advanced-deployments' },
            { text: 'custom-resource-definitions', link: '/th/k8s/custom-resource-definitions' },
            { text: 'scheduling', link: '/th/k8s/scheduling' },
            { text: 'security', link: '/th/k8s/security' },
            { text: 'deployment-patterns', link: '/th/k8s/deployment-patterns' },
            { text: 'backup-disaster-recovery', link: '/th/k8s/backup-disaster-recovery' },
            { text: 'multi-cluster-management', link: '/th/k8s/multi-cluster-management' },
            { text: 'helm', link: '/th/k8s/helm' },
          ],
          '/th/mongodb/': [
            { text: 'introduction-to-mongodb', link: '/th/mongodb/introduction-to-mongodb' },   
            { text: 'mongodb-architecture', link: '/th/mongodb/mongodb-architecture' }, 
            { text: 'database-and-collections', link: '/th/mongodb/database-and-collections' }, 
            { text: 'documents-and-bson', link: '/th/mongodb/documents-and-bson' }, 
            { text: 'basic-crud-operations', link: '/th/mongodb/basic-crud-operations' },
            { text: 'query-operators', link: '/th/mongodb/query-operators' },
            { text: 'mongodb-shell', link: '/th/mongodb/mongodb-shell' },
            { text: 'data-types', link: '/th/mongodb/data-types' },
            { text: 'indexes', link: '/th/mongodb/indexes' },
            { text: 'query-basics', link: '/th/mongodb/query-basics' },
            { text: 'aggregation-framework', link: '/th/mongodb/aggregation-framework' },
            { text: 'relationships', link: '/th/mongodb/relationships' },
            { text: 'transactions', link: '/th/mongodb/transactions' },
            { text: 'backup-and-restore', link: '/th/mongodb/backup-and-restore' },
            { text: 'schema-design', link: '/th/mongodb/schema-design' },
            { text: 'validation-rules', link: '/th/mongodb/validation-rules' },
            { text: 'replica-sets', link: '/th/mongodb/replica-sets' },
            { text: 'sharding', link: '/th/mongodb/sharding' },
            { text: 'performance-tuning', link: '/th/mongodb/performance-tuning' },
            { text: 'security', link: '/th/mongodb/security' },
            { text: 'advanced-aggregations', link: '/th/mongodb/advanced-aggregations' },
            { text: 'common-errors-debugging', link: '/th/mongodb/common-errors-debugging' },
          ],
          '/th/postgresql/': [
            { text: 'introduction-to-postgresql', link: '/th/postgresql/introduction-to-postgresql' },
            { text: 'postgresql-architecture', link: '/th/postgresql/postgresql-architecture' },
            { text: 'rdbms-concepts', link: '/th/postgresql/rdbms-concepts' },
            { text: 'object-model', link: '/th/postgresql/object-model' },
            { text: 'relational-model', link: '/th/postgresql/relational-model' },
            { text: 'high-level-database-concepts', link: '/th/postgresql/high-level-database-concepts' },
            { text: 'postgresql-tools', link: '/th/postgresql/postgresql-tools' },
            { text: 'basic-sql-commands', link: '/th/postgresql/basic-sql-commands' },
            { text: 'sorting-and-limiting', link: '/th/postgresql/sorting-and-limiting' },
            { text: 'basic-functions', link: '/th/postgresql/basic-functions' },
            { text: 'data-types', link: '/th/postgresql/data-types' },
            { text: 'constraints-and-keys', link: '/th/postgresql/constraints-and-keys' },
            { text: 'joins', link: '/th/postgresql/joins' },
            { text: 'aggregations', link: '/th/postgresql/aggregations' },
            { text: 'views', link: '/th/postgresql/views' },
            { text: 'indexing', link: '/th/postgresql/indexing' },
            { text: 'subqueries', link: '/th/postgresql/subqueries' },
            { text: 'stored-procedures', link: '/th/postgresql/stored-procedures' },
            { text: 'common-table-expressions', link: '/th/postgresql/common-table-expressions' },
            { text: 'transactions-and-acid-properties', link: '/th/postgresql/transactions-and-acid-properties' },
            { text: 'triggers', link: '/th/postgresql/triggers' },
            { text: 'json-and-jsonb', link: '/th/postgresql/json-and-jsonb' },
            { text: 'user-management', link: '/th/postgresql/user-management' },
            { text: 'backup-and-restore', link: '/th/postgresql/backup-and-restore' },
            { text: 'error-handling', link: '/th/postgresql/error-handling' },
            { text: 'authentication', link: '/th/postgresql/authentication' },
            { text: 'advanced-queries', link: '/th/postgresql/advanced-queries' },
            { text: 'data-security', link: '/th/postgresql/data-security' },
            { text: 'performance-optimization', link: '/th/postgresql/performance-optimization' },
            { text: 'replication', link: '/th/postgresql/replication' },
            { text: 'scaling', link: '/th/postgresql/scaling' },
          ],
          '/th/redis/': [
            { text: 'introduction-to-redis', link: '/th/redis/introduction-to-redis' },
            { text: 'in-memory-data-structure-store', link: '/th/redis/in-memory-data-structure-store' },
            { text: 'key-value-database', link: '/th/redis/key-value-database' },
            { text: 'cache', link: '/th/redis/cache' },
            { text: 'real-time-analytics', link: '/th/redis/real-time-analytics' },
            { text: 'session-management', link: '/th/redis/session-management' },
            { text: 'pub-sub-messaging', link: '/th/redis/pub-sub-messaging' },
            { text: 'leaderboards-and-counters', link: '/th/redis/leaderboards-and-counters' },
            { text: 'data-persistence-options', link: '/th/redis/data-persistence-options' },
            { text: 'rich-data-structures', link: '/th/redis/rich-data-structures' },
            { text: 'high-performance-and-scalability', link: '/th/redis/high-performance-and-scalability' },
            { text: 'redis-vs-sql-nosql-dbs', link: '/th/redis/redis-vs-sql-nosql-dbs' },
            { text: 'when-to-choose-redis', link: '/th/redis/when-to-choose-redis' },
            { text: 'using-package-managers', link: '/th/redis/using-package-managers' },
            { text: 'pre-compiled-binaries', link: '/th/redis/pre-compiled-binaries' },
            { text: 'using-docker', link: '/th/redis/using-docker' },
            { text: 'starting-the-server', link: '/th/redis/starting-the-server' },
            { text: 'connecting-using-redis-cli', link: '/th/redis/connecting-using-redis-cli' },
            { text: 'basic-commands-set-get', link: '/th/redis/basic-commands-set-get' },
            { text: 'del', link: '/th/redis/del' },
            { text: 'expire', link: '/th/redis/expire' },
            { text: 'ttl', link: '/th/redis/ttl' },
            { text: 'overview-of-data-types', link: '/th/redis/overview-of-data-types' },
            { text: 'strings', link: '/th/redis/strings' },
            { text: 'lists', link: '/th/redis/lists' },
            { text: 'sets', link: '/th/redis/sets' },
            { text: 'hashes', link: '/th/redis/hashes' },
            { text: 'sorted-sets', link: '/th/redis/sorted-sets' },
            { text: 'naming-conventions', link: '/th/redis/naming-conventions' },
            { text: 'retrieval-by-pattern', link: '/th/redis/retrieval-by-pattern' },
            { text: 'expiration', link: '/th/redis/expiration' },
            { text: 'atomicity-in-redis', link: '/th/redis/atomicity-in-redis' },
            { text: 'pipelining', link: '/th/redis/pipelining' },
            { text: 'batch-operations', link: '/th/redis/batch-operations' },
            { text: 'bitmaps', link: '/th/redis/bitmaps' },
            { text: 'hyperloglog', link: '/th/redis/hyperloglog' },
            { text: 'streams', link: '/th/redis/streams' },
            { text: 'geospatial-indexes', link: '/th/redis/geospatial-indexes' },
            { text: 'pub-sub', link: '/th/redis/pub-sub' },
            { text: 'transactions', link: '/th/redis/transactions' },
            { text: 'lua-scripting', link: '/th/redis/lua-scripting' },
            { text: 'persistence-options', link: '/th/redis/persistence-options' },
            { text: 'replication-basics', link: '/th/redis/replication-basics' },
            { text: 'sentinel', link: '/th/redis/sentinel' },
            { text: 'clustering', link: '/th/redis/clustering' },
            { text: 'ssl-tls-encryption', link: '/th/redis/ssl-tls-encryption' },
            { text: 'network-security', link: '/th/redis/network-security' },
            { text: 'authentication', link: '/th/redis/authentication' },
            { text: 'monitoring-and-optimization', link: '/th/redis/monitoring-and-optimization' },
            { text: 'modules', link: '/th/redis/modules' },
            { text: 'backup-and-recovery', link: '/th/redis/backup-and-recovery' },
            { text: 'upgrading-redis', link: '/th/redis/upgrading-redis' },
            { text: 'disaster-recovery', link: '/th/redis/disaster-recovery' },
          ],
          '/th/algorithm/': [
            { text: 'introduction-to-algorithms', link: '/th/algorithm/introduction-to-algorithms' },
            { text: 'time-and-space-complexity', link: '/th/algorithm/time-and-space-complexity' },
            { text: 'asymptotic-notations', link: '/th/algorithm/asymptotic-notations' },
            { text: 'arrays', link: '/th/algorithm/arrays' },
            { text: 'string', link: '/th/algorithm/string' },
            { text: 'linked-list', link: '/th/algorithm/linked-list' },
            { text: 'stacks-and-queues', link: '/th/algorithm/stacks-and-queues' },
            { text: 'recursion-and-divide-and-conquer-algorithms', link: '/th/algorithm/recursion-and-divide-and-conquer-algorithms' },
            { text: 'linear-search-and-binary-search', link: '/th/algorithm/linear-search-and-binary-search' },
            { text: 'sorting-algorithms', link: '/th/algorithm/sorting-algorithms' },
            { text: 'merge-sort-and-quick-sort', link: '/th/algorithm/merge-sort-and-quick-sort' },
            { text: 'heaps-and-priority-queues', link: '/th/algorithm/heaps-and-priority-queues' },
            { text: 'hashing-and-hash-tables', link: '/th/algorithm/hashing-and-hash-tables' },
            { text: 'dynamic-programming', link: '/th/algorithm/dynamic-programming' },
            { text: 'fibonacci-sequence-with-dp', link: '/th/algorithm/fibonacci-sequence-with-dp' },
            { text: 'longest-common-subsequence', link: '/th/algorithm/longest-common-subsequence' },
            { text: 'greedy-algorithms', link: '/th/algorithm/greedy-algorithms' },
            { text: 'knapsack-problem', link: '/th/algorithm/knapsack-problem' },
            { text: 'graph-algorithms', link: '/th/algorithm/graph-algorithms' },
            { text: 'backtracking-algorithms', link: '/th/algorithm/backtracking-algorithms' },
            { text: 'network-flow-algorithms', link: '/th/algorithm/network-flow-algorithms' },
            { text: 'string-matching-algorithms', link: '/th/algorithm/string-matching-algorithms' },
            { text: 'advanced-greedy-algorithms', link: '/th/algorithm/advanced-greedy-algorithms' },
          ],
          '/th/aws/': [
            { text: 'introduction-to-aws', link: '/th/aws/introduction-to-aws' },
            {
              text: 'Compute',
              collapsed: true,
              items: [
                { text: 'Compute', link: '/th/aws/compute/compute' },
                { text: 'EC2', link: '/th/aws/compute/ec2' },
                { text: 'Lightsail', link: '/th/aws/compute/lightsail' },
                { text: 'Lambda', link: '/th/aws/compute/lambda' },
                { text: 'Batch', link: '/th/aws/compute/batch' },
                { text: 'Elastic Beanstalk', link: '/th/aws/compute/elastic-beanstalk' },
                { text: 'Serverless Application', link: '/th/aws/compute/serverless-application' },
                { text: 'AWS Outposts', link: '/th/aws/compute/aws-outposts' },
                { text: 'EC2 Image Builder', link: '/th/aws/compute/ec2-image-builder' },
                { text: 'AWS App Runner', link: '/th/aws/compute/aws-app-runner' },
                { text: 'AWS SimSpace Weaver', link: '/th/aws/compute/aws-simspace-weaver' },
                { text: 'Parallel Computing Service', link: '/th/aws/compute/parallel-computing-service' },
                { text: 'EC2 Global View', link: '/th/aws/compute/ec2-global-view' },
              ]
            },
            {
              text: 'Containers',
              collapsed: true,
              items: [
                { text: 'Containers', link: '/th/aws/containers/containers' },
                { text: 'Elastic Container Service', link: '/th/aws/containers/elastic-container-service' },
                { text: 'Elastic Kubernetes Service', link: '/th/aws/containers/elastic-kubernetes-service' },
                { text: 'Red Hat OpenShift Service on AWS', link: '/th/aws/containers/red-hat-openshift-service-on-aws' },
                { text: 'Elastic Container Registry', link: '/th/aws/containers/elastic-container-registry' },
              ]
            },
            {
              text: "Storage",
              collapsed: true,
              items: [
                { text: 'Storage', link: '/th/aws/storage/storage' },
                { text: 'S3', link: '/th/aws/storage/s3' },
                { text: 'EFS', link: '/th/aws/storage/efs' },
                { text: 'FSx', link: '/th/aws/storage/fsx' },
                { text: 'S3 Glacier', link: '/th/aws/storage/s3-glacier' },
                { text: 'Storage Gateway', link: '/th/aws/storage/storage-gateway' },
                { text: 'AWS Backup', link: '/th/aws/storage/aws-backup' },
                { text: 'AWS Elastic Disaster Recovery', link: '/th/aws/storage/aws-elastic-disaster-recovery' },
              ]
            },
            {
              text: "Database",
              collapsed: true,
              items: [
                { text: 'Database', link: '/th/aws/database/database' },
                { text: 'Aurora and RDS', link: '/th/aws/database/aurora-and-rds' },
                { text: 'ElastiCache', link: '/th/aws/database/elasticache' },
                { text: 'Neptune', link: '/th/aws/database/neptune' },
                { text: 'Amazon QLDB', link: '/th/aws/database/amazon-qldb' },
                { text: 'Amazon DocumentDB', link: '/th/aws/database/amazon-documentdb' },
                { text: 'Amazon Keyspaces', link: '/th/aws/database/amazon-keyspaces' },
                { text: 'Amazon Timestream', link: '/th/aws/database/amazon-timestream' },
                { text: 'DynamoDB', link: '/th/aws/database/dynamodb' },
                { text: 'Aurora DSQL', link: '/th/aws/database/aurora-dsql' },
                { text: 'Amazon MemoryDB', link: '/th/aws/database/amazon-memorydb' },
                { text: 'Oracle Database@AWS', link: '/th/aws/database/oracle-database-aws' },
              ]              
            },
            {
              text: "Migration & Transfer",
              collapsed: true,
              items: [
                { text: 'Migration & Transfer', link: '/th/aws/migration-&-transfer/migration-&-transfer' },
                { text: 'AWS Migration Hub', link: '/th/aws/migration-&-transfer/aws-migration-hub' },
                { text: 'AWS Application Migration Service', link: '/th/aws/migration-&-transfer/aws-application-migration-service' },
                { text: 'Application Discovery Service', link: '/th/aws/migration-&-transfer/application-discovery-service' },
                { text: 'Database Migration Service', link: '/th/aws/migration-&-transfer/database-migration-service' },
                { text: 'AWS Transfer Family', link: '/th/aws/migration-&-transfer/aws-transfer-family' },
                { text: 'AWS Snow Family', link: '/th/aws/migration-&-transfer/aws-snow-family' },
                { text: 'DataSync', link: '/th/aws/migration-&-transfer/datasync' },
                { text: 'AWS Mainframe Modernization', link: '/th/aws/migration-&-transfer/aws-mainframe-modernization' },
                { text: 'Amazon Elastic VMware Service (Preview)', link: '/th/aws/migration-&-transfer/amazon-elastic-vmware-service' },
              ]
            },
            {
              text: "Networking & Content Delivery",
              collapsed: true,
              items: [
                { text: 'Networking & Content Delivery', link: '/th/aws/networking-&-content-delivery/networking-&-content-delivery' },
                { text: 'VPC', link: '/th/aws/networking-&-content-delivery/vpc' },
                { text: 'CloudFront', link: '/th/aws/networking-&-content-delivery/cloudfront' },
                { text: 'API Gateway', link: '/th/aws/networking-&-content-delivery/api-gateway' },
                { text: 'Direct Connect', link: '/th/aws/networking-&-content-delivery/direct-connect' },
                { text: 'AWS App Mesh', link: '/th/aws/networking-&-content-delivery/aws-app-mesh' },
                { text: 'Global Accelerator', link: '/th/aws/networking-&-content-delivery/global-accelerator' },
                { text: 'Route 53', link: '/th/aws/networking-&-content-delivery/route-53' },
                { text: 'AWS Data Transfer Terminal', link: '/th/aws/networking-&-content-delivery/aws-data-transfer-terminal' },
                { text: 'AWS Private 5G', link: '/th/aws/networking-&-content-delivery/aws-private-5g' },
                { text: 'AWS Cloud Map', link: '/th/aws/networking-&-content-delivery/aws-cloud-map' },
                { text: 'Application Recovery Controller', link: '/th/aws/networking-&-content-delivery/application-recovery-controller' },
              ]
            },
            {
              text: "Developer Tools",
              collapsed: true,
              items: [
                { text: 'Developer Tools', link: '/th/aws/developer-tools/developer-tools' },
                { text: 'CodeCommit', link: '/th/aws/developer-tools/codecommit' },
                { text: 'CodeBuild', link: '/th/aws/developer-tools/codebuild' },
                { text: 'CodeDeploy', link: '/th/aws/developer-tools/codedeploy' },
                { text: 'CodePipeline', link: '/th/aws/developer-tools/codepipeline' },
                { text: 'Cloud9', link: '/th/aws/developer-tools/cloud9' },
                { text: 'CloudShell', link: '/th/aws/developer-tools/cloudshell' },
                { text: 'X-Ray', link: '/th/aws/developer-tools/x-ray' },
                { text: 'AWS FIS', link: '/th/aws/developer-tools/aws-fis' },
                { text: 'Infrastructure Composer', link: '/th/aws/developer-tools/infrastructure-composer' },
                { text: 'AWS App Studio', link: '/th/aws/developer-tools/aws-app-studio' },
                { text: 'AWS AppConfig', link: '/th/aws/developer-tools/aws-appconfig' },
                { text: 'CodeArtifact', link: '/th/aws/developer-tools/codeartifact' },
                { text: 'Amazon CodeCatalyst', link: '/th/aws/developer-tools/amazon-codecatalyst' },
                { text: 'Amazon Q Developer', link: '/th/aws/developer-tools/amazon-q-developer' },
              ]
            },
            {
              text: "Customer Enablement",
              collapsed: true,
              items: [
                { text: 'Customer Enablement', link: '/th/aws/customer-enablement/customer-enablement' },
                { text: 'AWS IQ', link: '/th/aws/customer-enablement/aws-iq' },
                { text: 'Managed Services', link: '/th/aws/customer-enablement/managed-services' },
                { text: 'Activate for Startups', link: '/th/aws/customer-enablement/activate-for-startups' },
                { text: 'AWS re:Post Private', link: '/th/aws/customer-enablement/aws-re-post-private' },
                { text: 'Support', link: '/th/aws/customer-enablement/support' },
              ]
            },
            {
              text: "Robotics",
              collapsed: true,
              items: [
                { text: 'Robotics', link: '/th/aws/robotics/robotics' },
                { text: 'AWS RoboMaker', link: '/th/aws/robotics/aws-robomaker' },
              ]
            },
            {
              text: "Blockchain",
              collapsed: true,
              items: [
                { text: 'Blockchain', link: '/th/aws/blockchain/blockchain' },
                { text: 'Amazon Managed Blockchain', link: '/th/aws/blockchain/amazon-managed-blockchain' },
              ]
            },
            {
              text: "Satellite",
              collapsed: true,
              items: [
                { text: 'Satellite', link: '/th/aws/satellite/satellite' },
                { text: 'Ground Station', link: '/th/aws/satellite/ground-station' },
              ]
            },    
            {
              text: "Quantum Technologies",
              collapsed: true,
              items: [
                { text: 'Quantum Technologies', link: '/th/aws/quantum-technologies/quantum-technologies' },
                { text: 'Amazon Braket', link: '/th/aws/quantum-technologies/amazon-braket' },
              ]
            },    
            {
              text: "Management & Governance",
              collapsed: true,
              items: [
                { text: 'Management & Governance', link: '/th/aws/management-&-governance/management-&-governance' },
                { text: 'AWS Organizations', link: '/th/aws/management-&-governance/aws-organizations' },
                { text: 'CloudWatch', link: '/th/aws/management-&-governance/cloudwatch' },
                { text: 'AWS Auto Scaling', link: '/th/aws/management-&-governance/aws-auto-scaling' },
                { text: 'CloudFormation', link: '/th/aws/management-&-governance/cloudformation' },
                { text: 'AWS Config', link: '/th/aws/management-&-governance/aws-config' },
                { text: 'OpsWorks', link: '/th/aws/management-&-governance/opsworks' },
                { text: 'Service Catalog', link: '/th/aws/management-&-governance/service-catalog' },
                { text: 'Systems Manager', link: '/th/aws/management-&-governance/systems-manager' },
                { text: 'Trusted Advisor', link: '/th/aws/management-&-governance/trusted -advisor' },
                { text: 'Control Tower', link: '/th/aws/management-&-governance/control-tower' },
                { text: 'AWS Well-Architected Tool', link: '/th/aws/management-&-governance/aws-well-architected-tool' },
                { text: 'Amazon Q Developer in chat applications', link: '/th/aws/management-&-governance/amazon-q-developer-in-chat-applications' },
                { text: 'Launch Wizard', link: '/th/aws/management-&-governance/launch-wizard' },
                { text: 'AWS Compute Optimizer', link: '/th/aws/management-&-governance/aws-compute-optimizer' },
                { text: 'Resource Groups & Tag Editor', link: '/th/aws/management-&-governance/resource-groups-&-tag-editor' },
                { text: 'Amazon Grafana', link: '/th/aws/management-&-governance/amazon-grafana' },
                { text: 'Amazon Prometheus', link: '/th/aws/management-&-governance/amazon-prometheus' },
                { text: 'AWS Resilience Hub', link: '/th/aws/management-&-governance/aws-resilience-hub' },
                { text: 'Incident Manager', link: '/th/aws/management-&-governance/incident-manager' },
                { text: 'AWS Telco Network Builder', link: '/th/aws/management-&-governance/aws-telco-network-builder' },
                { text: 'AWS Health Dashboard', link: '/th/aws/management-&-governance/aws-health-dashboard' },
                { text: 'AWS Proton', link: '/th/aws/management-&-governance/aws-proton' },
                { text: 'AWS User Notifications', link: '/th/aws/management-&-governance/aws-user-notifications' },
                { text: 'CloudTrail', link: '/th/aws/management-&-governance/cloudtrail' },
                { text: 'AWS License Manager', link: '/th/aws/management-&-governance/aws-license-manager' },
                { text: 'AWS Resource Explorer', link: '/th/aws/management-&-governance/aws-resource-explorer' },
                { text: 'Service Quotas', link: '/th/aws/management-&-governance/service-quotas' },
              ]
            },        
            {
              text: "Media Services",
              collapsed: true,
              items: [
                { text: 'Media Services', link: '/th/aws/media-services/media-services' },
                { text: 'Kinesis Video Streams', link: '/th/aws/media-services/kinesis-video-streams' },
                { text: 'MediaConvert', link: '/th/aws/media-services/mediaconvert' },
                { text: 'MediaLive', link: '/th/aws/media-services/medialive' },
                { text: 'MediaPackage', link: '/th/aws/media-services/mediapackage' },
                { text: 'MediaStore', link: '/th/aws/media-services/mediastore' },
                { text: 'MediaTailor', link: '/th/aws/media-services/mediatailor' },
                { text: 'Elemental Appliances & Software', link: '/th/aws/media-services/elemental-appliances-&-software' },
                { text: 'Elastic Transcoder', link: '/th/aws/media-services/elastic-transcoder' },
                { text: 'Amazon Interactive Video Service', link: '/th/aws/media-services/amazon-interactive-video-service' },
                { text: 'AWS Deadline Cloud', link: '/th/aws/media-services/aws-deadline-cloud' },
                { text: 'MediaConnect', link: '/th/aws/media-services/mediaconnect' },
              ]
            },  
            {
              text: "Machine Learning",
              collapsed: true,
              items: [
                { text: 'Machine Learning', link: '/th/aws/machine-learning/machine-learning' },
                { text: 'Amazon SageMaker AI', link: '/th/aws/machine-learning/amazon-sagemaker-ai' },
                { text: 'Amazon Augmented AI', link: '/th/aws/machine-learning/amazon-augmented-ai' },
                { text: 'Amazon CodeGuru', link: '/th/aws/machine-learning/amazon-codeguru' },
                { text: 'Amazon DevOps Guru', link: '/th/aws/machine-learning/amazon-devops-guru' },
                { text: 'Amazon Comprehend', link: '/th/aws/machine-learning/amazon-comprehend' },
                { text: 'Amazon Forecast', link: '/th/aws/machine-learning/amazon-forecast' },
                { text: 'Amazon Fraud Detector', link: '/th/aws/machine-learning/amazon-fraud-detector' },
                { text: 'Amazon Kendra', link: '/th/aws/machine-learning/amazon-kendra' },
                { text: 'Amazon Personalize', link: '/th/aws/machine-learning/amazon-personalize' },
                { text: 'Amazon Polly', link: '/th/aws/machine-learning/amazon-polly' },
                { text: 'Amazon Rekognition', link: '/th/aws/machine-learning/amazon-rekognition' },
                { text: 'Amazon Textract', link: '/th/aws/machine-learning/amazon-textract' },
                { text: 'Amazon Transcribe', link: '/th/aws/machine-learning/amazon-transcribe' },
                { text: 'Amazon Translate', link: '/th/aws/machine-learning/amazon-translate' },
                { text: 'AWS DeepComposer', link: '/th/aws/machine-learning/aws-deepcomposer' },
                { text: 'AWS DeepRacer', link: '/th/aws/machine-learning/aws-deepracer' },
                { text: 'AWS Panorama', link: '/th/aws/machine-learning/aws-panorama' },
                { text: 'Amazon Monitron', link: '/th/aws/machine-learning/amazon-monitron' },
                { text: 'AWS HealthLake', link: '/th/aws/machine-learning/aws-healthlake' },
                { text: 'Amazon Lookout for Vision', link: '/th/aws/machine-learning/amazon-lookout-for-vision' },
                { text: 'Amazon Lookout for Equipment', link: '/th/aws/machine-learning/amazon-lookout-for-equipment' },
                { text: 'Amazon Lookout for Metrics', link: '/th/aws/machine-learning/amazon-lookout-for-metrics' },
                { text: 'Amazon Q Business', link: '/th/aws/machine-learning/amazon-q-business' },
                { text: 'AWS HealthOmics', link: '/th/aws/machine-learning/aws-healthomics' },
                { text: 'Amazon Bedrock', link: '/th/aws/machine-learning/amazon-bedrock' },
                { text: 'Amazon Q', link: '/th/aws/machine-learning/amazon-q' },
                { text: 'Amazon Comprehend Medical', link: '/th/aws/machine-learning/amazon-comprehend-medical' },
                { text: 'Amazon Lex', link: '/th/aws/machine-learning/amazon-lex' },
                { text: 'AWS HealthImaging', link: '/th/aws/machine-learning/aws-healthimaging' },
              ]
            },  
            {
              text: "Analytics",
              collapsed: true,
              items: [
                { text: 'Analytics', link: '/th/aws/analytics/analytics' },
                { text: 'Athena', link: '/th/aws/analytics/athena' },
                { text: 'Amazon Redshift', link: '/th/aws/analytics/amazon-redshift' },
                { text: 'CloudSearch', link: '/th/aws/analytics/cloudsearch' },
                { text: 'Amazon OpenSearch Service', link: '/th/aws/analytics/amazon-opensearch-service' },
                { text: 'Kinesis', link: '/th/aws/analytics/kinesis' },
                { text: 'QuickSight', link: '/th/aws/analytics/quicksight' },
                { text: 'AWS Data Exchange', link: '/th/aws/analytics/aws-data-exchange' },
                { text: 'AWS Lake Formation', link: '/th/aws/analytics/aws-lake-formation' },
                { text: 'MSK', link: '/th/aws/analytics/msk' },
                { text: 'AWS Glue DataBrew', link: '/th/aws/analytics/aws-glue-databrew' },
                { text: 'Amazon FinSpace', link: '/th/aws/analytics/amazon-finspace' },
                { text: 'Managed Apache Flink', link: '/th/aws/analytics/managed-apache-flink' },
                { text: 'EMR', link: '/th/aws/analytics/emr' },
                { text: 'AWS Clean Rooms', link: '/th/aws/analytics/aws-clean-rooms' },
                { text: 'Amazon SageMaker', link: '/th/aws/analytics/amazon-sagemaker' },
                { text: 'AWS Entity Resolution', link: '/th/aws/analytics/aws-entity-resolution' },
                { text: 'AWS Glue', link: '/th/aws/analytics/aws-glue' },
                { text: 'Amazon Data Firehose', link: '/th/aws/analytics/amazon-data-firehose' },
                { text: 'Amazon DataZone', link: '/th/aws/analytics/amazon-datazone' },
              ]
            },   
            {
              text: "Security, Identity, & Compliance",
              collapsed: true,
              items: [
                { text: 'Security, Identity, & Compliance', link: '/th/aws/security-identity-&-compliance/security-identity-&-compliance' },
                { text: 'Resource Access Manager', link: '/th/aws/security-identity-&-compliance/resource-access-manager' },
                { text: 'Cognito', link: '/th/aws/security-identity-&-compliance/cognito' },
                { text: 'Secrets Manager', link: '/th/aws/security-identity-&-compliance/secrets-manager' },
                { text: 'GuardDuty', link: '/th/aws/security-identity-&-compliance/guardduty' },
                { text: 'Amazon Inspector', link: '/th/aws/security-identity-&-compliance/amazon-inspector' },
                { text: 'Amazon Macie', link: '/th/aws/security-identity-&-compliance/amazon-macie' },
                { text: 'IAM Identity Center', link: '/th/aws/security-identity-&-compliance/iam-identity-center' },
                { text: 'Certificate Manager', link: '/th/aws/security-identity-&-compliance/certificate-manager' },
                { text: 'Key Management Service', link: '/th/aws/security-identity-&-compliance/key-management-service' },
                { text: 'CloudHSM', link: '/th/aws/security-identity-&-compliance/cloudhsm' },
                { text: 'Directory Service', link: '/th/aws/security-identity-&-compliance/directory-service' },
                { text: 'AWS Firewall Manager', link: '/th/aws/security-identity-&-compliance/aws-firewall-manager' },
                { text: 'AWS Artifact', link: '/th/aws/security-identity-&-compliance/aws-artifact' },
                { text: 'Detective', link: '/th/aws/security-identity-&-compliance/detective' },
                { text: 'AWS Signer', link: '/th/aws/security-identity-&-compliance/aws-signer' },
                { text: 'Security Lake', link: '/th/aws/security-identity-&-compliance/security-lake' },
                { text: 'WAF & Shield', link: '/th/aws/security-identity-&-compliance/waf-&-shield' },
                { text: 'Amazon Verified Permissions', link: '/th/aws/security-identity-&-compliance/amazon-verified-permissions' },
                { text: 'AWS Audit Manager', link: '/th/aws/security-identity-&-compliance/aws-audit-manager' },
                { text: 'Security Hub', link: '/th/aws/security-identity-&-compliance/security-hub' },
                { text: 'IAM', link: '/th/aws/security-identity-&-compliance/iam' },
                { text: 'AWS Private Certificate Authority', link: '/th/aws/security-identity-&-compliance/aws-private-certificate-authority' },
                { text: 'AWS Payment Cryptography', link: '/th/aws/security-identity-&-compliance/aws-payment-cryptography' },
                { text: 'AWS Security Incident Response', link: '/th/aws/security-identity-&-compliance/aws-security-incident-response' },
              ]
            },   
            {
              text: "Cloud Financial Management",
              collapsed: true,
              items: [
                { text: 'Cloud Financial Management', link: '/th/aws/cloud-financial-management/cloud-financial-management' },
                { text: 'AWS Marketplace', link: '/th/aws/cloud-financial-management/aws-marketplace' },
                { text: 'AWS Billing Conductor', link: '/th/aws/cloud-financial-management/aws-billing-conductor' },
                { text: 'Billing and Cost Management', link: '/th/aws/cloud-financial-management/billing-and-cost-management' },
              ]
            },     
            {
              text: "Front-end Web & Mobile",
              collapsed: true,
              items: [
                { text: 'Front-end Web & Mobile', link: '/th/aws/front-end-web-&-mobile/front-end-web-&-mobile' },
                { text: 'AWS Amplify', link: '/th/aws/front-end-web-&-mobile/aws-amplify' },
                { text: 'AWS AppSync', link: '/th/aws/front-end-web-&-mobile/aws-appsync' },
                { text: 'Device Farm', link: '/th/aws/front-end-web-&-mobile/device-farm' },
                { text: 'Amazon Location Service', link: '/th/aws/front-end-web-&-mobile/amazon-location-service' },
              ]
            },  
            {
              text: "Application Integration",
              collapsed: true,
              items: [
                { text: 'Application Integration', link: '/th/aws/application-integration/application-integration' },
                { text: 'Step Functions', link: '/th/aws/application-integration/step-functions' },
                { text: 'Amazon AppFlow', link: '/th/aws/application-integration/amazon-appflow' },
                { text: 'Amazon MQ', link: '/th/aws/application-integration/amazon-mq' },
                { text: 'Simple Notification Service', link: '/th/aws/application-integration/simple-notification-service' },
                { text: 'Simple Queue Service', link: '/th/aws/application-integration/simple-queue-service' },
                { text: 'SWF', link: '/th/aws/application-integration/swf' },
                { text: 'Managed Apache Airflow', link: '/th/aws/application-integration/managed-apache-airflow' },
                { text: 'AWS B2B Data Interchange', link: '/th/aws/application-integration/aws-b2b-data-interchange' },
                { text: 'Amazon EventBridge', link: '/th/aws/application-integration/amazon-eventbridge' },
              ]
            },  
            {
              text: "Business Applications",
              collapsed: true,
              items: [
                { text: 'Business Applications', link: '/th/aws/business-applications/business-applications' },
                { text: 'Amazon Connect', link: '/th/aws/business-applications/amazon-connect' },
                { text: 'Amazon Chime', link: '/th/aws/business-applications/amazon-chime' },
                { text: 'Amazon Simple Email Service', link: '/th/aws/business-applications/amazon-simple-email-service' },
                { text: 'Amazon WorkDocs', link: '/th/aws/business-applications/amazon-workdocs' },
                { text: 'Amazon WorkMail', link: '/th/aws/business-applications/amazon-workmail' },
                { text: 'AWS Supply Chain', link: '/th/aws/business-applications/aws-supply-chain' },
                { text: 'Amazon Pinpoint', link: '/th/aws/business-applications/amazon-pinpoint' },
                { text: 'Amazon One Enterprise', link: '/th/aws/business-applications/amazon-one-enterprise' },
                { text: 'AWS Wickr', link: '/th/aws/business-applications/aws-wickr' },
                { text: 'AWS AppFabric', link: '/th/aws/business-applications/aws-appfabric' },
                { text: 'AWS End User Messaging', link: '/th/aws/business-applications/aws-end-user-messaging' },
                { text: 'Amazon Chime SDK', link: '/th/aws/business-applications/amazon-chime-sdk' },
              ]
            },  
            {
              text: "End User Computing",
              collapsed: true,
              items: [
                { text: 'End User Computing', link: '/th/aws/end-user-computing/end-user-computing' },
                { text: 'WorkSpaces', link: '/th/aws/end-user-computing/workspaces' },
                { text: 'AppStream 2.0', link: '/th/aws/end-user-computing/appstream' },
                { text: 'WorkSpaces Thin Client', link: '/th/aws/end-user-computing/workspaces-thin-client' },
                { text: 'WorkSpaces Secure Browser', link: '/th/aws/end-user-computing/workspaces-secure-browser' },
              ]
            },  
            {
              text: "Internet of Things",
              collapsed: true,
              items: [
                { text: 'Internet of Things', link: '/th/aws/internet-of-things/internet-of-things' },
                { text: 'IoT Analytics', link: '/th/aws/internet-of-things/iot-analytics' },
                { text: 'IoT Device Defender', link: '/th/aws/internet-of-things/iot-device-defender' },
                { text: 'IoT Device Management', link: '/th/aws/internet-of-things/iot-device-management' },
                { text: 'IoT Greengrass', link: '/th/aws/internet-of-things/iot-greengrass' },
                { text: 'IoT SiteWise', link: '/th/aws/internet-of-things/iot-sitewise' },
                { text: 'IoT Core', link: '/th/aws/internet-of-things/iot-core' },
                { text: 'IoT TwinMaker', link: '/th/aws/internet-of-things/iot-twinmaker' },
                { text: 'IoT Events', link: '/th/aws/internet-of-things/iot-events' },
                { text: 'AWS IoT FleetWise', link: '/th/aws/internet-of-things/aws-iot-fleetwise' },
              ]
            },  
            {
              text: "Game Development",
              collapsed: true,
              items: [
                { text: 'Game Development', link: '/th/aws/game-development/game-development' },
                { text: 'Amazon GameLift Servers', link: '/th/aws/game-development/amazon-gamelift-servers' },
                { text: 'Amazon GameLift Streams', link: '/th/aws/game-development/amazon-gamelift-streams' },
              ]
            },                                   
          ]          
        }
      }
    }
  }
})
