export const TH = [
    { text: 'introduction-to-git', link: '/th/git-&-github/introduction-to-git' },
    { text: 'repository-initialization', link: '/th/git-&-github/repository-initialization' },
    { text: 'git-status-&-staging-area', link: '/th/git-&-github/git-status-&-staging-area' },
    { text: 'git-commit-&-history', link: '/th/git-&-github/git-commit-&-history' },
    { text: 'git-branching', link: '/th/git-&-github/git-branching' },
    { text: 'git-merging', link: '/th/git-&-github/git-merging' },
    { text: 'handling-merge-conflicts', link: '/th/git-&-github/handling-merge-conflicts' },
    { text: 'git-rebase', link: '/th/git-&-github/git-rebase' },
    { text: 'git-reset-checkout', link: '/th/git-&-github/git-reset-checkout' },
    { text: 'git-stash', link: '/th/git-&-github/git-stash' },
    { text: 'introduction-to-github', link: '/th/git-&-github/introduction-to-github' },
    { text: 'pushing-to-github', link: '/th/git-&-github/pushing-to-github' },
    { text: 'pull-requests', link: '/th/git-&-github/pull-requests' },
    { text: 'collaborating-with-teams', link: '/th/git-&-github/collaborating-with-teams' },
    { text: 'github-actions', link: '/th/git-&-github/github-actions' },
    { text: 'git-submodules', link: '/th/git-&-github/git-submodules' },
    { text: 'git-tags', link: '/th/git-&-github/git-tags' },
    { text: 'git-hooks', link: '/th/git-&-github/git-hooks' },
    { text: 'cherry-picking-changes', link: '/th/git-&-github/cherry-picking-changes' },
    { text: 'git-bisect', link: '/th/git-&-github/git-bisect' },
    { text: 'git-with-large-project', link: '/th/git-&-github/git-with-large-project' },
    { text: 'git-with-ci-cd', link: '/th/git-&-github/git-with-ci-cd' },
    { text: 'reverting-changes-and-handling-history', link: '/th/git-&-github/reverting-changes-and-handling-history' },
    { text: 'git-workflow-for-teams', link: '/th/git-&-github/git-workflow-for-teams' },
    { text: 'handling-multiple-remotes', link: '/th/git-&-github/handling-multiple-remotes' },
]